packages:
  - 'packages/kit'
  - 'packages/localnet'
  - 'packages/scenario'
  - 'packages/api'
  - 'packages/authorisation'
  - 'packages/endpoints'
  - 'packages/ipfs'
  - 'packages/types'
  - 'docs'
  - 'packages/generated_clients/jobs'
  - 'packages/generated_clients/stake'
  - 'packages/generated_clients/merkle_distributor'
