/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLAWBACK_DISCRIMINATOR = new Uint8Array([
  111, 92, 142, 79, 33, 234, 82, 27,
]);

export function getClawbackDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CLAWBACK_DISCRIMINATOR);
}

export type ClawbackInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountDistributor extends string | IAccountMeta<string> = string,
  TAccountFrom extends string | IAccountMeta<string> = string,
  TAccountTo extends string | IAccountMeta<string> = string,
  TAccountClaimant extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountDistributor extends string
        ? WritableAccount<TAccountDistributor>
        : TAccountDistributor,
      TAccountFrom extends string
        ? WritableAccount<TAccountFrom>
        : TAccountFrom,
      TAccountTo extends string ? WritableAccount<TAccountTo> : TAccountTo,
      TAccountClaimant extends string
        ? ReadonlySignerAccount<TAccountClaimant> &
            IAccountSignerMeta<TAccountClaimant>
        : TAccountClaimant,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ClawbackInstructionData = { discriminator: ReadonlyUint8Array };

export type ClawbackInstructionDataArgs = {};

export function getClawbackInstructionDataEncoder(): Encoder<ClawbackInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLAWBACK_DISCRIMINATOR })
  );
}

export function getClawbackInstructionDataDecoder(): Decoder<ClawbackInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getClawbackInstructionDataCodec(): Codec<
  ClawbackInstructionDataArgs,
  ClawbackInstructionData
> {
  return combineCodec(
    getClawbackInstructionDataEncoder(),
    getClawbackInstructionDataDecoder()
  );
}

export type ClawbackInput<
  TAccountDistributor extends string = string,
  TAccountFrom extends string = string,
  TAccountTo extends string = string,
  TAccountClaimant extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** The [MerkleDistributor]. */
  distributor: Address<TAccountDistributor>;
  /** Distributor ATA containing the tokens to distribute. */
  from: Address<TAccountFrom>;
  /** The Clawback token account. */
  to: Address<TAccountTo>;
  /**
   * Claimant account
   * Anyone can claw back the funds
   */
  claimant: TransactionSigner<TAccountClaimant>;
  /** The [System] program. */
  systemProgram?: Address<TAccountSystemProgram>;
  /** SPL [Token] program. */
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getClawbackInstruction<
  TAccountDistributor extends string,
  TAccountFrom extends string,
  TAccountTo extends string,
  TAccountClaimant extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
>(
  input: ClawbackInput<
    TAccountDistributor,
    TAccountFrom,
    TAccountTo,
    TAccountClaimant,
    TAccountSystemProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): ClawbackInstruction<
  TProgramAddress,
  TAccountDistributor,
  TAccountFrom,
  TAccountTo,
  TAccountClaimant,
  TAccountSystemProgram,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    distributor: { value: input.distributor ?? null, isWritable: true },
    from: { value: input.from ?? null, isWritable: true },
    to: { value: input.to ?? null, isWritable: true },
    claimant: { value: input.claimant ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.distributor),
      getAccountMeta(accounts.from),
      getAccountMeta(accounts.to),
      getAccountMeta(accounts.claimant),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getClawbackInstructionDataEncoder().encode({}),
  } as ClawbackInstruction<
    TProgramAddress,
    TAccountDistributor,
    TAccountFrom,
    TAccountTo,
    TAccountClaimant,
    TAccountSystemProgram,
    TAccountTokenProgram
  >;

  return instruction;
}

export type ParsedClawbackInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The [MerkleDistributor]. */
    distributor: TAccountMetas[0];
    /** Distributor ATA containing the tokens to distribute. */
    from: TAccountMetas[1];
    /** The Clawback token account. */
    to: TAccountMetas[2];
    /**
     * Claimant account
     * Anyone can claw back the funds
     */

    claimant: TAccountMetas[3];
    /** The [System] program. */
    systemProgram: TAccountMetas[4];
    /** SPL [Token] program. */
    tokenProgram: TAccountMetas[5];
  };
  data: ClawbackInstructionData;
};

export function parseClawbackInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedClawbackInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      distributor: getNextAccount(),
      from: getNextAccount(),
      to: getNextAccount(),
      claimant: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getClawbackInstructionDataDecoder().decode(instruction.data),
  };
}
