/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLOSE_DISTRIBUTOR_DISCRIMINATOR = new Uint8Array([
  202, 56, 180, 143, 46, 104, 106, 112,
]);

export function getCloseDistributorDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLOSE_DISTRIBUTOR_DISCRIMINATOR
  );
}

export type CloseDistributorInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountDistributor extends string | IAccountMeta<string> = string,
  TAccountTokenVault extends string | IAccountMeta<string> = string,
  TAccountAdmin extends string | IAccountMeta<string> = string,
  TAccountDestinationTokenAccount extends
    | string
    | IAccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountDistributor extends string
        ? WritableAccount<TAccountDistributor>
        : TAccountDistributor,
      TAccountTokenVault extends string
        ? WritableAccount<TAccountTokenVault>
        : TAccountTokenVault,
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            IAccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountDestinationTokenAccount extends string
        ? WritableAccount<TAccountDestinationTokenAccount>
        : TAccountDestinationTokenAccount,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CloseDistributorInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type CloseDistributorInstructionDataArgs = {};

export function getCloseDistributorInstructionDataEncoder(): Encoder<CloseDistributorInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLOSE_DISTRIBUTOR_DISCRIMINATOR })
  );
}

export function getCloseDistributorInstructionDataDecoder(): Decoder<CloseDistributorInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCloseDistributorInstructionDataCodec(): Codec<
  CloseDistributorInstructionDataArgs,
  CloseDistributorInstructionData
> {
  return combineCodec(
    getCloseDistributorInstructionDataEncoder(),
    getCloseDistributorInstructionDataDecoder()
  );
}

export type CloseDistributorInput<
  TAccountDistributor extends string = string,
  TAccountTokenVault extends string = string,
  TAccountAdmin extends string = string,
  TAccountDestinationTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** [MerkleDistributor]. */
  distributor: Address<TAccountDistributor>;
  /** Clawback receiver token account */
  tokenVault: Address<TAccountTokenVault>;
  /**
   * Admin wallet, responsible for creating the distributor and paying for the transaction.
   * Also has the authority to set the clawback receiver and change itself.
   */
  admin: TransactionSigner<TAccountAdmin>;
  /** account receive token back */
  destinationTokenAccount: Address<TAccountDestinationTokenAccount>;
  /** The [Token] program. */
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getCloseDistributorInstruction<
  TAccountDistributor extends string,
  TAccountTokenVault extends string,
  TAccountAdmin extends string,
  TAccountDestinationTokenAccount extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
>(
  input: CloseDistributorInput<
    TAccountDistributor,
    TAccountTokenVault,
    TAccountAdmin,
    TAccountDestinationTokenAccount,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CloseDistributorInstruction<
  TProgramAddress,
  TAccountDistributor,
  TAccountTokenVault,
  TAccountAdmin,
  TAccountDestinationTokenAccount,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    distributor: { value: input.distributor ?? null, isWritable: true },
    tokenVault: { value: input.tokenVault ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: true },
    destinationTokenAccount: {
      value: input.destinationTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.distributor),
      getAccountMeta(accounts.tokenVault),
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.destinationTokenAccount),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getCloseDistributorInstructionDataEncoder().encode({}),
  } as CloseDistributorInstruction<
    TProgramAddress,
    TAccountDistributor,
    TAccountTokenVault,
    TAccountAdmin,
    TAccountDestinationTokenAccount,
    TAccountTokenProgram
  >;

  return instruction;
}

export type ParsedCloseDistributorInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** [MerkleDistributor]. */
    distributor: TAccountMetas[0];
    /** Clawback receiver token account */
    tokenVault: TAccountMetas[1];
    /**
     * Admin wallet, responsible for creating the distributor and paying for the transaction.
     * Also has the authority to set the clawback receiver and change itself.
     */

    admin: TAccountMetas[2];
    /** account receive token back */
    destinationTokenAccount: TAccountMetas[3];
    /** The [Token] program. */
    tokenProgram: TAccountMetas[4];
  };
  data: CloseDistributorInstructionData;
};

export function parseCloseDistributorInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedCloseDistributorInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      distributor: getNextAccount(),
      tokenVault: getNextAccount(),
      admin: getNextAccount(),
      destinationTokenAccount: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getCloseDistributorInstructionDataDecoder().decode(instruction.data),
  };
}
