/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLOSE_CLAIM_STATUS_DISCRIMINATOR = new Uint8Array([
  163, 214, 191, 165, 245, 188, 17, 185,
]);

export function getCloseClaimStatusDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLOSE_CLAIM_STATUS_DISCRIMINATOR
  );
}

export type CloseClaimStatusInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountClaimStatus extends string | IAccountMeta<string> = string,
  TAccountClaimant extends string | IAccountMeta<string> = string,
  TAccountAdmin extends string | IAccountMeta<string> = string,
  TAccountDistributor extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountClaimStatus extends string
        ? WritableAccount<TAccountClaimStatus>
        : TAccountClaimStatus,
      TAccountClaimant extends string
        ? WritableAccount<TAccountClaimant>
        : TAccountClaimant,
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            IAccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountDistributor extends string
        ? ReadonlyAccount<TAccountDistributor>
        : TAccountDistributor,
      ...TRemainingAccounts,
    ]
  >;

export type CloseClaimStatusInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type CloseClaimStatusInstructionDataArgs = {};

export function getCloseClaimStatusInstructionDataEncoder(): Encoder<CloseClaimStatusInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLOSE_CLAIM_STATUS_DISCRIMINATOR })
  );
}

export function getCloseClaimStatusInstructionDataDecoder(): Decoder<CloseClaimStatusInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCloseClaimStatusInstructionDataCodec(): Codec<
  CloseClaimStatusInstructionDataArgs,
  CloseClaimStatusInstructionData
> {
  return combineCodec(
    getCloseClaimStatusInstructionDataEncoder(),
    getCloseClaimStatusInstructionDataDecoder()
  );
}

export type CloseClaimStatusInput<
  TAccountClaimStatus extends string = string,
  TAccountClaimant extends string = string,
  TAccountAdmin extends string = string,
  TAccountDistributor extends string = string,
> = {
  claimStatus: Address<TAccountClaimStatus>;
  claimant: Address<TAccountClaimant>;
  admin: TransactionSigner<TAccountAdmin>;
  distributor: Address<TAccountDistributor>;
};

export function getCloseClaimStatusInstruction<
  TAccountClaimStatus extends string,
  TAccountClaimant extends string,
  TAccountAdmin extends string,
  TAccountDistributor extends string,
  TProgramAddress extends Address = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
>(
  input: CloseClaimStatusInput<
    TAccountClaimStatus,
    TAccountClaimant,
    TAccountAdmin,
    TAccountDistributor
  >,
  config?: { programAddress?: TProgramAddress }
): CloseClaimStatusInstruction<
  TProgramAddress,
  TAccountClaimStatus,
  TAccountClaimant,
  TAccountAdmin,
  TAccountDistributor
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    claimStatus: { value: input.claimStatus ?? null, isWritable: true },
    claimant: { value: input.claimant ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: false },
    distributor: { value: input.distributor ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.claimStatus),
      getAccountMeta(accounts.claimant),
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.distributor),
    ],
    programAddress,
    data: getCloseClaimStatusInstructionDataEncoder().encode({}),
  } as CloseClaimStatusInstruction<
    TProgramAddress,
    TAccountClaimStatus,
    TAccountClaimant,
    TAccountAdmin,
    TAccountDistributor
  >;

  return instruction;
}

export type ParsedCloseClaimStatusInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    claimStatus: TAccountMetas[0];
    claimant: TAccountMetas[1];
    admin: TAccountMetas[2];
    distributor: TAccountMetas[3];
  };
  data: CloseClaimStatusInstructionData;
};

export function parseCloseClaimStatusInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedCloseClaimStatusInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      claimStatus: getNextAccount(),
      claimant: getNextAccount(),
      admin: getNextAccount(),
      distributor: getNextAccount(),
    },
    data: getCloseClaimStatusInstructionDataDecoder().decode(instruction.data),
  };
}
