/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const NEW_CLAIM_DISCRIMINATOR = new Uint8Array([
  78, 177, 98, 123, 210, 21, 187, 83,
]);

export function getNewClaimDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(NEW_CLAIM_DISCRIMINATOR);
}

export type NewClaimInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountDistributor extends string | IAccountMeta<string> = string,
  TAccountClaimStatus extends string | IAccountMeta<string> = string,
  TAccountFrom extends string | IAccountMeta<string> = string,
  TAccountTo extends string | IAccountMeta<string> = string,
  TAccountClaimant extends string | IAccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountDistributor extends string
        ? WritableAccount<TAccountDistributor>
        : TAccountDistributor,
      TAccountClaimStatus extends string
        ? WritableAccount<TAccountClaimStatus>
        : TAccountClaimStatus,
      TAccountFrom extends string
        ? WritableAccount<TAccountFrom>
        : TAccountFrom,
      TAccountTo extends string ? WritableAccount<TAccountTo> : TAccountTo,
      TAccountClaimant extends string
        ? WritableSignerAccount<TAccountClaimant> &
            IAccountSignerMeta<TAccountClaimant>
        : TAccountClaimant,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type NewClaimInstructionData = {
  discriminator: ReadonlyUint8Array;
  amountUnlocked: bigint;
  amountLocked: bigint;
  proof: Array<ReadonlyUint8Array>;
};

export type NewClaimInstructionDataArgs = {
  amountUnlocked: number | bigint;
  amountLocked: number | bigint;
  proof: Array<ReadonlyUint8Array>;
};

export function getNewClaimInstructionDataEncoder(): Encoder<NewClaimInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['amountUnlocked', getU64Encoder()],
      ['amountLocked', getU64Encoder()],
      ['proof', getArrayEncoder(fixEncoderSize(getBytesEncoder(), 32))],
    ]),
    (value) => ({ ...value, discriminator: NEW_CLAIM_DISCRIMINATOR })
  );
}

export function getNewClaimInstructionDataDecoder(): Decoder<NewClaimInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['amountUnlocked', getU64Decoder()],
    ['amountLocked', getU64Decoder()],
    ['proof', getArrayDecoder(fixDecoderSize(getBytesDecoder(), 32))],
  ]);
}

export function getNewClaimInstructionDataCodec(): Codec<
  NewClaimInstructionDataArgs,
  NewClaimInstructionData
> {
  return combineCodec(
    getNewClaimInstructionDataEncoder(),
    getNewClaimInstructionDataDecoder()
  );
}

export type NewClaimInput<
  TAccountDistributor extends string = string,
  TAccountClaimStatus extends string = string,
  TAccountFrom extends string = string,
  TAccountTo extends string = string,
  TAccountClaimant extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** The [MerkleDistributor]. */
  distributor: Address<TAccountDistributor>;
  /** Claim status PDA */
  claimStatus: Address<TAccountClaimStatus>;
  /** Distributor ATA containing the tokens to distribute. */
  from: Address<TAccountFrom>;
  /** Account to send the claimed tokens to. */
  to: Address<TAccountTo>;
  /** Who is claiming the tokens. */
  claimant: TransactionSigner<TAccountClaimant>;
  /** SPL [Token] program. */
  tokenProgram?: Address<TAccountTokenProgram>;
  /** The [System] program. */
  systemProgram?: Address<TAccountSystemProgram>;
  amountUnlocked: NewClaimInstructionDataArgs['amountUnlocked'];
  amountLocked: NewClaimInstructionDataArgs['amountLocked'];
  proof: NewClaimInstructionDataArgs['proof'];
};

export function getNewClaimInstruction<
  TAccountDistributor extends string,
  TAccountClaimStatus extends string,
  TAccountFrom extends string,
  TAccountTo extends string,
  TAccountClaimant extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
>(
  input: NewClaimInput<
    TAccountDistributor,
    TAccountClaimStatus,
    TAccountFrom,
    TAccountTo,
    TAccountClaimant,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): NewClaimInstruction<
  TProgramAddress,
  TAccountDistributor,
  TAccountClaimStatus,
  TAccountFrom,
  TAccountTo,
  TAccountClaimant,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    distributor: { value: input.distributor ?? null, isWritable: true },
    claimStatus: { value: input.claimStatus ?? null, isWritable: true },
    from: { value: input.from ?? null, isWritable: true },
    to: { value: input.to ?? null, isWritable: true },
    claimant: { value: input.claimant ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.distributor),
      getAccountMeta(accounts.claimStatus),
      getAccountMeta(accounts.from),
      getAccountMeta(accounts.to),
      getAccountMeta(accounts.claimant),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getNewClaimInstructionDataEncoder().encode(
      args as NewClaimInstructionDataArgs
    ),
  } as NewClaimInstruction<
    TProgramAddress,
    TAccountDistributor,
    TAccountClaimStatus,
    TAccountFrom,
    TAccountTo,
    TAccountClaimant,
    TAccountTokenProgram,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedNewClaimInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The [MerkleDistributor]. */
    distributor: TAccountMetas[0];
    /** Claim status PDA */
    claimStatus: TAccountMetas[1];
    /** Distributor ATA containing the tokens to distribute. */
    from: TAccountMetas[2];
    /** Account to send the claimed tokens to. */
    to: TAccountMetas[3];
    /** Who is claiming the tokens. */
    claimant: TAccountMetas[4];
    /** SPL [Token] program. */
    tokenProgram: TAccountMetas[5];
    /** The [System] program. */
    systemProgram: TAccountMetas[6];
  };
  data: NewClaimInstructionData;
};

export function parseNewClaimInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedNewClaimInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      distributor: getNextAccount(),
      claimStatus: getNextAccount(),
      from: getNextAccount(),
      to: getNextAccount(),
      claimant: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getNewClaimInstructionDataDecoder().decode(instruction.data),
  };
}
