/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS } from '../programs/index.js';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared/index.js';

export const NEW_DISTRIBUTOR_INSTRUCTION_ACCOUNTS = {
  distributor: 0,
  clawbackReceiver: 1,
  mint: 2,
  tokenVault: 3,
  admin: 4,
  systemProgram: 5,
  associatedTokenProgram: 6,
  tokenProgram: 7,
} as const;

export type NewDistributorInstructionAccountName = keyof typeof NEW_DISTRIBUTOR_INSTRUCTION_ACCOUNTS;
export const NEW_DISTRIBUTOR_DISCRIMINATOR = new Uint8Array([
  32, 139, 112, 171, 0, 2, 225, 155,
]);

export function getNewDistributorDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    NEW_DISTRIBUTOR_DISCRIMINATOR
  );
}

export type NewDistributorInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountDistributor extends string | AccountMeta<string> = string,
  TAccountClawbackReceiver extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountTokenVault extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountDistributor extends string
        ? WritableAccount<TAccountDistributor>
        : TAccountDistributor,
      TAccountClawbackReceiver extends string
        ? WritableAccount<TAccountClawbackReceiver>
        : TAccountClawbackReceiver,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountTokenVault extends string
        ? ReadonlyAccount<TAccountTokenVault>
        : TAccountTokenVault,
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type NewDistributorInstructionData = {
  discriminator: ReadonlyUint8Array;
  version: bigint;
  root: ReadonlyUint8Array;
  maxTotalClaim: bigint;
  maxNumNodes: bigint;
  startVestingTs: bigint;
  endVestingTs: bigint;
  clawbackStartTs: bigint;
  enableSlot: bigint;
  closable: boolean;
};

export type NewDistributorInstructionDataArgs = {
  version: number | bigint;
  root: ReadonlyUint8Array;
  maxTotalClaim: number | bigint;
  maxNumNodes: number | bigint;
  startVestingTs: number | bigint;
  endVestingTs: number | bigint;
  clawbackStartTs: number | bigint;
  enableSlot: number | bigint;
  closable: boolean;
};

export function getNewDistributorInstructionDataEncoder(): FixedSizeEncoder<NewDistributorInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['version', getU64Encoder()],
      ['root', fixEncoderSize(getBytesEncoder(), 32)],
      ['maxTotalClaim', getU64Encoder()],
      ['maxNumNodes', getU64Encoder()],
      ['startVestingTs', getI64Encoder()],
      ['endVestingTs', getI64Encoder()],
      ['clawbackStartTs', getI64Encoder()],
      ['enableSlot', getU64Encoder()],
      ['closable', getBooleanEncoder()],
    ]),
    (value) => ({ ...value, discriminator: NEW_DISTRIBUTOR_DISCRIMINATOR })
  );
}

export function getNewDistributorInstructionDataDecoder(): FixedSizeDecoder<NewDistributorInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['version', getU64Decoder()],
    ['root', fixDecoderSize(getBytesDecoder(), 32)],
    ['maxTotalClaim', getU64Decoder()],
    ['maxNumNodes', getU64Decoder()],
    ['startVestingTs', getI64Decoder()],
    ['endVestingTs', getI64Decoder()],
    ['clawbackStartTs', getI64Decoder()],
    ['enableSlot', getU64Decoder()],
    ['closable', getBooleanDecoder()],
  ]);
}

export function getNewDistributorInstructionDataCodec(): FixedSizeCodec<
  NewDistributorInstructionDataArgs,
  NewDistributorInstructionData
> {
  return combineCodec(
    getNewDistributorInstructionDataEncoder(),
    getNewDistributorInstructionDataDecoder()
  );
}

export type NewDistributorInput<
  TAccountDistributor extends string = string,
  TAccountClawbackReceiver extends string = string,
  TAccountMint extends string = string,
  TAccountTokenVault extends string = string,
  TAccountAdmin extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** [MerkleDistributor]. */
  distributor: Address<TAccountDistributor>;
  /** Clawback receiver token account */
  clawbackReceiver: Address<TAccountClawbackReceiver>;
  /** The mint to distribute. */
  mint: Address<TAccountMint>;
  /**
   * Token vault
   * Should create previously
   */
  tokenVault: Address<TAccountTokenVault>;
  /**
   * Admin wallet, responsible for creating the distributor and paying for the transaction.
   * Also has the authority to set the clawback receiver and change itself.
   */
  admin: TransactionSigner<TAccountAdmin>;
  /** The [System] program. */
  systemProgram?: Address<TAccountSystemProgram>;
  /** The [Associated Token] program. */
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
  /** The [Token] program. */
  tokenProgram?: Address<TAccountTokenProgram>;
  version: NewDistributorInstructionDataArgs['version'];
  root: NewDistributorInstructionDataArgs['root'];
  maxTotalClaim: NewDistributorInstructionDataArgs['maxTotalClaim'];
  maxNumNodes: NewDistributorInstructionDataArgs['maxNumNodes'];
  startVestingTs: NewDistributorInstructionDataArgs['startVestingTs'];
  endVestingTs: NewDistributorInstructionDataArgs['endVestingTs'];
  clawbackStartTs: NewDistributorInstructionDataArgs['clawbackStartTs'];
  enableSlot: NewDistributorInstructionDataArgs['enableSlot'];
  closable: NewDistributorInstructionDataArgs['closable'];
};

export function getNewDistributorInstruction<
  TAccountDistributor extends string,
  TAccountClawbackReceiver extends string,
  TAccountMint extends string,
  TAccountTokenVault extends string,
  TAccountAdmin extends string,
  TAccountSystemProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
>(
  input: NewDistributorInput<
    TAccountDistributor,
    TAccountClawbackReceiver,
    TAccountMint,
    TAccountTokenVault,
    TAccountAdmin,
    TAccountSystemProgram,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): NewDistributorInstruction<
  TProgramAddress,
  TAccountDistributor,
  TAccountClawbackReceiver,
  TAccountMint,
  TAccountTokenVault,
  TAccountAdmin,
  TAccountSystemProgram,
  TAccountAssociatedTokenProgram,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    distributor: { value: input.distributor ?? null, isWritable: true },
    clawbackReceiver: {
      value: input.clawbackReceiver ?? null,
      isWritable: true,
    },
    mint: { value: input.mint ?? null, isWritable: false },
    tokenVault: { value: input.tokenVault ?? null, isWritable: false },
    admin: { value: input.admin ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.distributor),
      getAccountMeta(accounts.clawbackReceiver),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.tokenVault),
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getNewDistributorInstructionDataEncoder().encode(
      args as NewDistributorInstructionDataArgs
    ),
    programAddress,
  } as NewDistributorInstruction<
    TProgramAddress,
    TAccountDistributor,
    TAccountClawbackReceiver,
    TAccountMint,
    TAccountTokenVault,
    TAccountAdmin,
    TAccountSystemProgram,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram
  >);
}

export type ParsedNewDistributorInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** [MerkleDistributor]. */
    distributor: TAccountMetas[0];
    /** Clawback receiver token account */
    clawbackReceiver: TAccountMetas[1];
    /** The mint to distribute. */
    mint: TAccountMetas[2];
    /**
     * Token vault
     * Should create previously
     */
    tokenVault: TAccountMetas[3];
    /**
     * Admin wallet, responsible for creating the distributor and paying for the transaction.
     * Also has the authority to set the clawback receiver and change itself.
     */
    admin: TAccountMetas[4];
    /** The [System] program. */
    systemProgram: TAccountMetas[5];
    /** The [Associated Token] program. */
    associatedTokenProgram: TAccountMetas[6];
    /** The [Token] program. */
    tokenProgram: TAccountMetas[7];
  };
  data: NewDistributorInstructionData;
};

export function parseNewDistributorInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedNewDistributorInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      distributor: getNextAccount(),
      clawbackReceiver: getNextAccount(),
      mint: getNextAccount(),
      tokenVault: getNextAccount(),
      admin: getNextAccount(),
      systemProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getNewDistributorInstructionDataDecoder().decode(instruction.data),
  };
}
