/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SET_ADMIN_DISCRIMINATOR = new Uint8Array([
  251, 163, 0, 52, 91, 194, 187, 92,
]);

export function getSetAdminDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(SET_ADMIN_DISCRIMINATOR);
}

export type SetAdminInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountDistributor extends string | IAccountMeta<string> = string,
  TAccountAdmin extends string | IAccountMeta<string> = string,
  TAccountNewAdmin extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountDistributor extends string
        ? WritableAccount<TAccountDistributor>
        : TAccountDistributor,
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            IAccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountNewAdmin extends string
        ? WritableAccount<TAccountNewAdmin>
        : TAccountNewAdmin,
      ...TRemainingAccounts,
    ]
  >;

export type SetAdminInstructionData = { discriminator: ReadonlyUint8Array };

export type SetAdminInstructionDataArgs = {};

export function getSetAdminInstructionDataEncoder(): Encoder<SetAdminInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: SET_ADMIN_DISCRIMINATOR })
  );
}

export function getSetAdminInstructionDataDecoder(): Decoder<SetAdminInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getSetAdminInstructionDataCodec(): Codec<
  SetAdminInstructionDataArgs,
  SetAdminInstructionData
> {
  return combineCodec(
    getSetAdminInstructionDataEncoder(),
    getSetAdminInstructionDataDecoder()
  );
}

export type SetAdminInput<
  TAccountDistributor extends string = string,
  TAccountAdmin extends string = string,
  TAccountNewAdmin extends string = string,
> = {
  /** The [MerkleDistributor]. */
  distributor: Address<TAccountDistributor>;
  /** Admin signer */
  admin: TransactionSigner<TAccountAdmin>;
  /** New admin account */
  newAdmin: Address<TAccountNewAdmin>;
};

export function getSetAdminInstruction<
  TAccountDistributor extends string,
  TAccountAdmin extends string,
  TAccountNewAdmin extends string,
  TProgramAddress extends Address = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
>(
  input: SetAdminInput<TAccountDistributor, TAccountAdmin, TAccountNewAdmin>,
  config?: { programAddress?: TProgramAddress }
): SetAdminInstruction<
  TProgramAddress,
  TAccountDistributor,
  TAccountAdmin,
  TAccountNewAdmin
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    distributor: { value: input.distributor ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: true },
    newAdmin: { value: input.newAdmin ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.distributor),
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.newAdmin),
    ],
    programAddress,
    data: getSetAdminInstructionDataEncoder().encode({}),
  } as SetAdminInstruction<
    TProgramAddress,
    TAccountDistributor,
    TAccountAdmin,
    TAccountNewAdmin
  >;

  return instruction;
}

export type ParsedSetAdminInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The [MerkleDistributor]. */
    distributor: TAccountMetas[0];
    /** Admin signer */
    admin: TAccountMetas[1];
    /** New admin account */
    newAdmin: TAccountMetas[2];
  };
  data: SetAdminInstructionData;
};

export function parseSetAdminInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedSetAdminInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      distributor: getNextAccount(),
      admin: getNextAccount(),
      newAdmin: getNextAccount(),
    },
    data: getSetAdminInstructionDataDecoder().decode(instruction.data),
  };
}
