/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS } from '../programs/index.js';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared/index.js';

export const SET_CLAWBACK_RECEIVER_INSTRUCTION_ACCOUNTS = {
  distributor: 0,
  newClawbackAccount: 1,
  admin: 2,
} as const;

export type SetClawbackReceiverInstructionAccountName = keyof typeof SET_CLAWBACK_RECEIVER_INSTRUCTION_ACCOUNTS;
export const SET_CLAWBACK_RECEIVER_DISCRIMINATOR = new Uint8Array([
  153, 217, 34, 20, 19, 29, 229, 75,
]);

export function getSetClawbackReceiverDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_CLAWBACK_RECEIVER_DISCRIMINATOR
  );
}

export type SetClawbackReceiverInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountDistributor extends string | AccountMeta<string> = string,
  TAccountNewClawbackAccount extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountDistributor extends string
        ? WritableAccount<TAccountDistributor>
        : TAccountDistributor,
      TAccountNewClawbackAccount extends string
        ? ReadonlyAccount<TAccountNewClawbackAccount>
        : TAccountNewClawbackAccount,
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      ...TRemainingAccounts,
    ]
  >;

export type SetClawbackReceiverInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type SetClawbackReceiverInstructionDataArgs = {};

export function getSetClawbackReceiverInstructionDataEncoder(): FixedSizeEncoder<SetClawbackReceiverInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: SET_CLAWBACK_RECEIVER_DISCRIMINATOR,
    })
  );
}

export function getSetClawbackReceiverInstructionDataDecoder(): FixedSizeDecoder<SetClawbackReceiverInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getSetClawbackReceiverInstructionDataCodec(): FixedSizeCodec<
  SetClawbackReceiverInstructionDataArgs,
  SetClawbackReceiverInstructionData
> {
  return combineCodec(
    getSetClawbackReceiverInstructionDataEncoder(),
    getSetClawbackReceiverInstructionDataDecoder()
  );
}

export type SetClawbackReceiverInput<
  TAccountDistributor extends string = string,
  TAccountNewClawbackAccount extends string = string,
  TAccountAdmin extends string = string,
> = {
  /** The [MerkleDistributor]. */
  distributor: Address<TAccountDistributor>;
  /** New clawback account */
  newClawbackAccount: Address<TAccountNewClawbackAccount>;
  /** Admin signer */
  admin: TransactionSigner<TAccountAdmin>;
};

export function getSetClawbackReceiverInstruction<
  TAccountDistributor extends string,
  TAccountNewClawbackAccount extends string,
  TAccountAdmin extends string,
  TProgramAddress extends Address = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
>(
  input: SetClawbackReceiverInput<
    TAccountDistributor,
    TAccountNewClawbackAccount,
    TAccountAdmin
  >,
  config?: { programAddress?: TProgramAddress }
): SetClawbackReceiverInstruction<
  TProgramAddress,
  TAccountDistributor,
  TAccountNewClawbackAccount,
  TAccountAdmin
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    distributor: { value: input.distributor ?? null, isWritable: true },
    newClawbackAccount: {
      value: input.newClawbackAccount ?? null,
      isWritable: false,
    },
    admin: { value: input.admin ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.distributor),
      getAccountMeta(accounts.newClawbackAccount),
      getAccountMeta(accounts.admin),
    ],
    data: getSetClawbackReceiverInstructionDataEncoder().encode({}),
    programAddress,
  } as SetClawbackReceiverInstruction<
    TProgramAddress,
    TAccountDistributor,
    TAccountNewClawbackAccount,
    TAccountAdmin
  >);
}

export type ParsedSetClawbackReceiverInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The [MerkleDistributor]. */
    distributor: TAccountMetas[0];
    /** New clawback account */
    newClawbackAccount: TAccountMetas[1];
    /** Admin signer */
    admin: TAccountMetas[2];
  };
  data: SetClawbackReceiverInstructionData;
};

export function parseSetClawbackReceiverInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedSetClawbackReceiverInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      distributor: getNextAccount(),
      newClawbackAccount: getNextAccount(),
      admin: getNextAccount(),
    },
    data: getSetClawbackReceiverInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
