/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS } from '../programs/index.js';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared/index.js';

export const SET_ENABLE_SLOT_DISCRIMINATOR = new Uint8Array([
  5, 52, 73, 33, 150, 115, 97, 206,
]);

export function getSetEnableSlotDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_ENABLE_SLOT_DISCRIMINATOR
  );
}

export type SetEnableSlotInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountDistributor extends string | AccountMeta<string> = string,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountDistributor extends string
        ? WritableAccount<TAccountDistributor>
        : TAccountDistributor,
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      ...TRemainingAccounts,
    ]
  >;

export type SetEnableSlotInstructionData = {
  discriminator: ReadonlyUint8Array;
  enableSlot: bigint;
};

export type SetEnableSlotInstructionDataArgs = { enableSlot: number | bigint };

export function getSetEnableSlotInstructionDataEncoder(): FixedSizeEncoder<SetEnableSlotInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['enableSlot', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_ENABLE_SLOT_DISCRIMINATOR })
  );
}

export function getSetEnableSlotInstructionDataDecoder(): FixedSizeDecoder<SetEnableSlotInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['enableSlot', getU64Decoder()],
  ]);
}

export function getSetEnableSlotInstructionDataCodec(): FixedSizeCodec<
  SetEnableSlotInstructionDataArgs,
  SetEnableSlotInstructionData
> {
  return combineCodec(
    getSetEnableSlotInstructionDataEncoder(),
    getSetEnableSlotInstructionDataDecoder()
  );
}

export type SetEnableSlotInput<
  TAccountDistributor extends string = string,
  TAccountAdmin extends string = string,
> = {
  /** [MerkleDistributor]. */
  distributor: Address<TAccountDistributor>;
  /** Payer to create the distributor. */
  admin: TransactionSigner<TAccountAdmin>;
  enableSlot: SetEnableSlotInstructionDataArgs['enableSlot'];
};

export function getSetEnableSlotInstruction<
  TAccountDistributor extends string,
  TAccountAdmin extends string,
  TProgramAddress extends Address = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
>(
  input: SetEnableSlotInput<TAccountDistributor, TAccountAdmin>,
  config?: { programAddress?: TProgramAddress }
): SetEnableSlotInstruction<
  TProgramAddress,
  TAccountDistributor,
  TAccountAdmin
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    distributor: { value: input.distributor ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.distributor),
      getAccountMeta(accounts.admin),
    ],
    data: getSetEnableSlotInstructionDataEncoder().encode(
      args as SetEnableSlotInstructionDataArgs
    ),
    programAddress,
  } as SetEnableSlotInstruction<
    TProgramAddress,
    TAccountDistributor,
    TAccountAdmin
  >);
}

export type ParsedSetEnableSlotInstruction<
  TProgram extends string = typeof MERKLE_DISTRIBUTOR_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** [MerkleDistributor]. */
    distributor: TAccountMetas[0];
    /** Payer to create the distributor. */
    admin: TAccountMetas[1];
  };
  data: SetEnableSlotInstructionData;
};

export function parseSetEnableSlotInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedSetEnableSlotInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { distributor: getNextAccount(), admin: getNextAccount() },
    data: getSetEnableSlotInstructionDataDecoder().decode(instruction.data),
  };
}
