/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * Placeholder schema for the Host Manager API.
 * Replace with actual generated schema when available.
 */

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface paths {}

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface components {}
