/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { NOSANA_JOBS_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const OPEN_DISCRIMINATOR = new Uint8Array([
  228, 220, 155, 71, 199, 189, 60, 45,
]);

export function getOpenDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(OPEN_DISCRIMINATOR);
}

export type OpenInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountMint extends string | IAccountMeta<string> = string,
  TAccountMarket extends string | IAccountMeta<string> = string,
  TAccountVault extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TAccountAccessKey extends string | IAccountMeta<string> = string,
  TAccountRent extends
    | string
    | IAccountMeta<string> = 'SysvarRent111111111111111111111111111111111',
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountMarket extends string
        ? WritableSignerAccount<TAccountMarket> &
            IAccountSignerMeta<TAccountMarket>
        : TAccountMarket,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountAccessKey extends string
        ? ReadonlyAccount<TAccountAccessKey>
        : TAccountAccessKey,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type OpenInstructionData = {
  discriminator: ReadonlyUint8Array;
  jobExpiration: bigint;
  jobPrice: bigint;
  jobTimeout: bigint;
  jobType: number;
  nodeXnosMinimum: bigint;
};

export type OpenInstructionDataArgs = {
  jobExpiration: number | bigint;
  jobPrice: number | bigint;
  jobTimeout: number | bigint;
  jobType: number;
  nodeXnosMinimum: number | bigint;
};

export function getOpenInstructionDataEncoder(): Encoder<OpenInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['jobExpiration', getI64Encoder()],
      ['jobPrice', getU64Encoder()],
      ['jobTimeout', getI64Encoder()],
      ['jobType', getU8Encoder()],
      ['nodeXnosMinimum', getU128Encoder()],
    ]),
    (value) => ({ ...value, discriminator: OPEN_DISCRIMINATOR })
  );
}

export function getOpenInstructionDataDecoder(): Decoder<OpenInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['jobExpiration', getI64Decoder()],
    ['jobPrice', getU64Decoder()],
    ['jobTimeout', getI64Decoder()],
    ['jobType', getU8Decoder()],
    ['nodeXnosMinimum', getU128Decoder()],
  ]);
}

export function getOpenInstructionDataCodec(): Codec<
  OpenInstructionDataArgs,
  OpenInstructionData
> {
  return combineCodec(
    getOpenInstructionDataEncoder(),
    getOpenInstructionDataDecoder()
  );
}

export type OpenInput<
  TAccountMint extends string = string,
  TAccountMarket extends string = string,
  TAccountVault extends string = string,
  TAccountAuthority extends string = string,
  TAccountAccessKey extends string = string,
  TAccountRent extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  mint: Address<TAccountMint>;
  market: TransactionSigner<TAccountMarket>;
  vault: Address<TAccountVault>;
  authority: TransactionSigner<TAccountAuthority>;
  accessKey: Address<TAccountAccessKey>;
  rent?: Address<TAccountRent>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  jobExpiration: OpenInstructionDataArgs['jobExpiration'];
  jobPrice: OpenInstructionDataArgs['jobPrice'];
  jobTimeout: OpenInstructionDataArgs['jobTimeout'];
  jobType: OpenInstructionDataArgs['jobType'];
  nodeXnosMinimum: OpenInstructionDataArgs['nodeXnosMinimum'];
};

export function getOpenInstruction<
  TAccountMint extends string,
  TAccountMarket extends string,
  TAccountVault extends string,
  TAccountAuthority extends string,
  TAccountAccessKey extends string,
  TAccountRent extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
>(
  input: OpenInput<
    TAccountMint,
    TAccountMarket,
    TAccountVault,
    TAccountAuthority,
    TAccountAccessKey,
    TAccountRent,
    TAccountSystemProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): OpenInstruction<
  TProgramAddress,
  TAccountMint,
  TAccountMarket,
  TAccountVault,
  TAccountAuthority,
  TAccountAccessKey,
  TAccountRent,
  TAccountSystemProgram,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOSANA_JOBS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    mint: { value: input.mint ?? null, isWritable: false },
    market: { value: input.market ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
    accessKey: { value: input.accessKey ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.rent.value) {
    accounts.rent.value =
      'SysvarRent111111111111111111111111111111111' as Address<'SysvarRent111111111111111111111111111111111'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.accessKey),
      getAccountMeta(accounts.rent),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getOpenInstructionDataEncoder().encode(
      args as OpenInstructionDataArgs
    ),
  } as OpenInstruction<
    TProgramAddress,
    TAccountMint,
    TAccountMarket,
    TAccountVault,
    TAccountAuthority,
    TAccountAccessKey,
    TAccountRent,
    TAccountSystemProgram,
    TAccountTokenProgram
  >;

  return instruction;
}

export type ParsedOpenInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    mint: TAccountMetas[0];
    market: TAccountMetas[1];
    vault: TAccountMetas[2];
    authority: TAccountMetas[3];
    accessKey: TAccountMetas[4];
    rent: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
    tokenProgram: TAccountMetas[7];
  };
  data: OpenInstructionData;
};

export function parseOpenInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedOpenInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      mint: getNextAccount(),
      market: getNextAccount(),
      vault: getNextAccount(),
      authority: getNextAccount(),
      accessKey: getNextAccount(),
      rent: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getOpenInstructionDataDecoder().decode(instruction.data),
  };
}
