include:
  - local: .gitlab/ci/common.yml
  - project: nosana-ci/tools/cicd/gitlab-ci
    file: docker-container.yml

stages:
  - lint
  - build
  - test
  - deploy

variables:
  DOCKERFILE_DIR: ./packages/localnet/
  CONTAINER_PLATFORMS: linux/amd64
  REG_REPOSITORY: nosana/localnet

localnet:npm format:
  image: node:22.22.0
  stage: lint
  script:
    - pnpm install --frozen-lockfile
    - pnpm --filter @nosana/localnet run format
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

localnet:npm lint:
  image: node:22.22.0
  stage: lint
  script:
    - pnpm install --frozen-lockfile
    - pnpm --filter @nosana/localnet run lint
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

localnet:npm build:
  image: node:22.22.0
  stage: lint
  script:
    - pnpm install --frozen-lockfile
    - pnpm --filter @nosana/localnet run build
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
