include:
  - local: .gitlab/ci/common.yml

stages:
  - lint
  - build
  - test

localnet:npm format:
  stage: lint
  script:
    - pnpm install --frozen-lockfile
    - pnpm --filter @nosana/localnet run format
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

localnet:npm lint:
  stage: lint
  script:
    - pnpm install --frozen-lockfile
    - pnpm --filter @nosana/localnet run lint
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

localnet:npm build:
  stage: build
  script:
    - pnpm install --frozen-lockfile
    - pnpm --filter @nosana/localnet run build
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
