/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/deployments/jobs/{job}/job-definition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the job definition for a job. */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Signed authentication message, */
                    authorization: string;
                };
                path: {
                    job: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job definition details. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobDefinition"];
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/jobs/{job}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Post results for your running job. */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Signed authentication message, */
                    authorization: string;
                };
                path: {
                    job: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["JobResults"];
                };
            };
            responses: {
                /** @description Job results details. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            message: "Success";
                        };
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all user deployments. */
        get: {
            parameters: {
                query?: {
                    /** @description Base64-encoded cursor for keyset pagination */
                    cursor?: string;
                    /** @description Number of items per page (10, 20, 50, or 100) */
                    limit?: 10 | 20 | 50 | 100 | "10" | "20" | "50" | "100";
                    /** @description Sort order: 'asc' (oldest first) or 'desc' (newest first) */
                    sort_order?: "asc" | "desc";
                    /** @description Search for partial matches in deployment ID or name (case-insensitive) */
                    search?: string;
                    /** @description Filter by exact deployment ID */
                    id?: string;
                    /** @description Filter by exact deployment name */
                    name?: string;
                    /** @description Filter by deployment status. Can be single value or comma-separated list */
                    status?: ("DRAFT" | "ERROR" | "STARTING" | "RUNNING" | "STOPPING" | "STOPPED" | "INSUFFICIENT_FUNDS" | "ARCHIVED") | string;
                    /** @description Filter by deployment strategy. Can be single value or comma-separated list */
                    strategy?: ("SIMPLE" | "SIMPLE-EXTEND" | "SCHEDULED" | "INFINITE") | string;
                    /** @description Filter by vault public key */
                    vault?: string;
                    /** @description Filter deployments created after this date (ISO 8601 format) */
                    created_after?: string;
                    /** @description Filter deployments created before this date (ISO 8601 format) */
                    created_before?: string;
                };
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of deployments with pagination. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            deployments: components["schemas"]["Deployment"][];
                            pagination: {
                                /** @description Cursor for next page, null if no more pages */
                                cursor_next: string | null;
                                /** @description Cursor for previous page, null if on first page */
                                cursor_prev: string | null;
                                /** @description Total number of items in collection */
                                total_items: number;
                            };
                        };
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a specific deployment by ID. */
        get: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gets a deployment by ID. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Deployment"];
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Delete a deployment permanently */
        delete: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deployment deleted successfully. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get scheduled tasks for a specific deployment. */
        get: {
            parameters: {
                query?: {
                    /** @description Base64-encoded cursor for keyset pagination */
                    cursor?: string;
                    /** @description Number of items per page (10, 20, 50, or 100) */
                    limit?: 10 | 20 | 50 | 100 | "10" | "20" | "50" | "100";
                    /** @description Sort order: 'asc' (oldest first) or 'desc' (newest first) */
                    sort_order?: "asc" | "desc";
                    /** @description Filter by task type. Can be single value or comma-separated list */
                    task?: ("LIST" | "EXTEND" | "STOP") | string;
                    /** @description Filter tasks due after this date (ISO 8601 format) */
                    due_after?: string;
                    /** @description Filter tasks due before this date (ISO 8601 format) */
                    due_before?: string;
                };
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of scheduled tasks for the deployment with pagination. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tasks: components["schemas"]["Task"][];
                            pagination: {
                                /** @description Cursor for next page, null if no more pages */
                                cursor_next: string | null;
                                /** @description Cursor for previous page, null if on first page */
                                cursor_prev: string | null;
                                /** @description Total number of items in collection */
                                total_items: number;
                            };
                        };
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment}/header": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get header for a specific deployment. */
        get: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns authorization header to interact with the vaults jobs. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            header: string;
                        };
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment}/jobs/{job}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a specific deployment job by ID. */
        get: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                    job: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gets a deployment job by ID. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            confidential: boolean;
                            revision: number;
                            market: string;
                            node: string;
                            state: string | number;
                            jobStatus: string | null;
                            jobDefinition: components["schemas"]["JobDefinition"];
                            jobResult: components["schemas"]["JobResults"] | null;
                            timeStart: number;
                            timeEnd: number;
                            listedAt: number;
                        };
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get jobs for a specific deployment. */
        get: {
            parameters: {
                query?: {
                    /** @description Base64-encoded cursor for keyset pagination */
                    cursor?: string;
                    /** @description Number of items per page (10, 20, 50, or 100) */
                    limit?: 10 | 20 | 50 | 100 | "10" | "20" | "50" | "100";
                    /** @description Sort order: 'asc' (oldest first) or 'desc' (newest first) */
                    sort_order?: "asc" | "desc";
                    /** @description Filter by job state. Can be single value or comma-separated list (e.g., 'RUNNING,COMPLETED') */
                    state?: ("QUEUED" | "RUNNING" | "COMPLETED" | "STOPPED") | string;
                    /** @description Filter by exact job ID */
                    job?: string;
                    /** @description Filter by deployment revision number */
                    revision?: number;
                    /** @description Filter jobs created after this date (ISO 8601 format) */
                    created_after?: string;
                    /** @description Filter jobs created before this date (ISO 8601 format) */
                    created_before?: string;
                };
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of jobs for the deployment with pagination. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            jobs: components["schemas"]["Job"][];
                            pagination: {
                                /** @description Cursor for next page, null if no more pages */
                                cursor_next: string | null;
                                /** @description Cursor for previous page, null if on first page */
                                cursor_prev: string | null;
                                /** @description Total number of items in collection */
                                total_items: number;
                            };
                        };
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get revisions for a specific deployment. */
        get: {
            parameters: {
                query?: {
                    /** @description Base64-encoded cursor for keyset pagination */
                    cursor?: string;
                    /** @description Number of items per page (10, 20, 50, or 100) */
                    limit?: 10 | 20 | 50 | 100 | "10" | "20" | "50" | "100";
                    /** @description Sort order: 'asc' (oldest first) or 'desc' (newest first) */
                    sort_order?: "asc" | "desc";
                    /** @description Filter by exact revision number */
                    revision?: number;
                    /** @description Filter revisions created after this date (ISO 8601 format) */
                    created_after?: string;
                    /** @description Filter revisions created before this date (ISO 8601 format) */
                    created_before?: string;
                };
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of revisions for the deployment with pagination. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            revisions: components["schemas"]["Revision"][];
                            pagination: {
                                /** @description Cursor for next page, null if no more pages */
                                cursor_next: string | null;
                                /** @description Cursor for previous page, null if on first page */
                                cursor_prev: string | null;
                                /** @description Total number of items in collection */
                                total_items: number;
                            };
                        };
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get events for a specific deployment. */
        get: {
            parameters: {
                query?: {
                    /** @description Base64-encoded cursor for keyset pagination */
                    cursor?: string;
                    /** @description Number of items per page (10, 20, 50, or 100) */
                    limit?: 10 | 20 | 50 | 100 | "10" | "20" | "50" | "100";
                    /** @description Sort order: 'asc' (oldest first) or 'desc' (newest first) */
                    sort_order?: "asc" | "desc";
                    /** @description Filter by event category: 'Deployment' or 'Event'. Can be comma-separated list */
                    category?: ("Deployment" | "Event") | string;
                    /** @description Filter by event type. Can be single value or comma-separated list */
                    type?: string;
                    /** @description Filter events created after this date (ISO 8601 format) */
                    created_after?: string;
                    /** @description Filter events created before this date (ISO 8601 format) */
                    created_before?: string;
                };
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of events for the deployment with pagination. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            events: components["schemas"]["Event"][];
                            pagination: {
                                /** @description Cursor for next page, null if no more pages */
                                cursor_next: string | null;
                                /** @description Cursor for previous page, null if on first page */
                                cursor_prev: string | null;
                                /** @description Total number of items in collection */
                                total_items: number;
                            };
                        };
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new deployment. */
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DeploymentCreateBody"];
                };
            };
            responses: {
                /** @description Deployment created successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Deployment"];
                    };
                };
                /** @description Invalid request body. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment}/create-revision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new deployment revision. */
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["JobDefinition"];
                };
            };
            responses: {
                /** @description Deployment CreateRevisioned successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            active_revision: number;
                            endpoints: {
                                opId: string;
                                port: number | string;
                                url: string;
                            }[];
                            revisions: {
                                revision: number;
                                deployment: string;
                                ipfs_definition_hash: string;
                                job_definition: components["schemas"]["JobDefinition"];
                                /** Format: date-time */
                                created_at: string;
                            }[];
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Start an existing deployment. */
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deployment started successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "STARTING";
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Stop a deployment */
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deployment stopped successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "STOPPING";
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Archive a deployment */
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deployment archived successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ARCHIVED";
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment}/update-name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update the name of a deployment */
        patch: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Deployment name updated successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name: string;
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/deployments/{deployment}/update-active-revision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update deployment active revision. */
        patch: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        active_revision: number;
                    };
                };
            };
            responses: {
                /** @description Deployment active revision updated successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            active_revision: number;
                            endpoints: components["schemas"]["Endpoint"][];
                            updated_at: string;
                        };
                    };
                };
                /** @description Bad Request. Invalid input data. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/deployments/{deployment}/update-replica-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update the replica count of a deployment */
        patch: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        replicas: number;
                    };
                };
            };
            responses: {
                /** @description Deployment replica count updated successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            replicas: number;
                            /** Format: date-time */
                            updated_at: string;
                        };
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/deployments/{deployment}/update-schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update deployment schedule. */
        patch: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Cron expression for scheduled deployments */
                        schedule: string;
                    };
                };
            };
            responses: {
                /** @description Deployment schedule updated successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Cron expression for scheduled deployments */
                            schedule: string;
                            updated_at: string;
                        };
                    };
                };
                /** @description Bad Request. Invalid input data. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/deployments/{deployment}/update-timeout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update deployment timeout */
        patch: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    deployment: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        timeout: number;
                    };
                };
            };
            responses: {
                /** @description Deployment timeout updated successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            timeout: number;
                            updated_at: string;
                        };
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Deployment not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/deployments/vaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all user vaults. */
        get: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of vaults. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vaults"];
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/vaults/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a shared vault. */
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vault created successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vault"];
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/vaults/{vault}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Withdraw from a vault. */
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-user-id": string;
                    /** @description Signed authentication message, */
                    authorization: string;
                    /** @description Nosana API key */
                    "x-nosana-api"?: string;
                };
                path: {
                    vault: components["schemas"]["PublicKey"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        SOL?: number;
                        NOS?: number;
                    };
                };
            };
            responses: {
                /** @description Withdrawal successful. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            transaction: string;
                        };
                    };
                };
                /** @description Invalid request body. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized. Invalid or missing authentication. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": "Unauthorized";
                    };
                };
                /** @description Vault not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Headers
         * @description Headers for deployment routes
         */
        Headers: {
            "x-user-id": string;
            /** @description Signed authentication message, */
            authorization: string;
            /** @description Nosana API key */
            "x-nosana-api"?: string;
        };
        /**
         * HostHeaders
         * @description Headers for deployment routes
         */
        HostHeaders: {
            /** @description Signed authentication message, */
            authorization: string;
        };
        /** Deployment */
        Deployment: {
            id: string;
            name: string;
            vault: string;
            market: string;
            owner: string;
            status: "DRAFT" | "ERROR" | "STARTING" | "RUNNING" | "STOPPING" | "STOPPED" | "INSUFFICIENT_FUNDS" | "ARCHIVED";
            replicas: number;
            timeout: number;
            endpoints: {
                opId: string;
                port: number | string;
                url: string;
            }[];
            confidential: boolean;
            active_revision: number;
            active_jobs: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        } & ({
            strategy: "SIMPLE" | "SIMPLE-EXTEND";
        } | {
            /** @enum {string} */
            strategy: "SCHEDULED";
            /** @description Cron expression for scheduled deployments */
            schedule: string;
        } | {
            timeout: number;
            /** @enum {string} */
            strategy: "INFINITE";
            rotation_time: number;
        });
        /** Deployments */
        Deployments: components["schemas"]["Deployment"][];
        /** DeploymentStatus */
        DeploymentStatus: "DRAFT" | "ERROR" | "STARTING" | "RUNNING" | "STOPPING" | "STOPPED" | "INSUFFICIENT_FUNDS" | "ARCHIVED";
        /** DeploymentStrategy */
        DeploymentStrategy: "SIMPLE" | "SIMPLE-EXTEND" | "SCHEDULED" | "INFINITE";
        /** DeploymentCreateBody */
        DeploymentCreateBody: {
            name: string;
            market: string;
            replicas: number;
            /** @description Timeout in minutes, must be at least 1 minute. */
            timeout: number;
            vault?: string;
            confidential?: boolean;
            job_definition: components["schemas"]["JobDefinition"];
        } & ({
            strategy: "SIMPLE" | "SIMPLE-EXTEND";
        } | {
            /** @enum {string} */
            strategy: "SCHEDULED";
            /** @description Cron expression for scheduled deployments */
            schedule: string;
        } | {
            /** @description Timeout in minutes, must be at least 60 minute. */
            timeout: number;
            /** @enum {string} */
            strategy: "INFINITE";
            /** @description Rotation time in seconds. Must be at least 10 minutes less than timeout to allow for proper rotation. */
            rotation_time?: number;
        });
        /** Endpoint */
        Endpoint: {
            opId: string;
            port: number | string;
            url: string;
        };
        /** Error */
        Error: {
            error: string;
        };
        /** Event */
        Event: {
            category: "Deployment" | "Event";
            deploymentId: string;
            type: string;
            message: string;
            tx?: string;
            /** Format: date-time */
            created_at: string;
        };
        /** Job */
        Job: {
            tx: string;
            deployment: string;
            job: string;
            market: string;
            node: string | null;
            revision: number;
            state: "QUEUED" | "RUNNING" | "COMPLETED" | "STOPPED";
            time_start: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** PublicKey */
        PublicKey: string;
        /** Task */
        Task: {
            task: "LIST" | "EXTEND" | "STOP";
            deploymentId: string;
            tx?: string;
            job?: string;
            limit?: number;
            active_revision?: number;
            /** Format: date-time */
            due_at: string;
            /** Format: date-time */
            created_at: string;
        };
        /** Vault */
        Vault: {
            vault: string;
            owner: string;
            /** Format: date-time */
            created_at: string;
        };
        /** Vaults */
        Vaults: {
            vault: string;
            owner: string;
            /** Format: date-time */
            created_at: string;
        }[];
        /** Revision */
        Revision: {
            revision: number;
            deployment: string;
            ipfs_definition_hash: string;
            job_definition: components["schemas"]["JobDefinition"];
            /** Format: date-time */
            created_at: string;
        };
        /** JobDefinition */
        JobDefinition: {
            /** @enum {string} */
            version: "0.1";
            /** @enum {string} */
            type: "container";
            logistics?: {
                send: {
                    /**
                     * @description api        - we receive and send via an endpoint endpoint
                     *     api-listen - we create an endpoint to listen for incoming requests
                     * @enum {string}
                     */
                    type: "api" | "api-listen";
                    /** @description Make all properties in T optional */
                    args: {
                        endpoint?: string;
                    };
                };
                receive: {
                    /**
                     * @description api        - we receive and send via an endpoint endpoint
                     *     api-listen - we create an endpoint to listen for incoming requests
                     * @enum {string}
                     */
                    type: "api" | "api-listen";
                    /** @description Make all properties in T optional */
                    args: {
                        endpoint?: string;
                    };
                };
            };
            deployment_id?: string;
            ssh?: {
                public_keys?: string[];
            };
            meta?: {
                trigger?: string;
                /** @description Construct a type with a set of properties K of type T */
                system_resources?: {
                    [key: string]: string | number;
                };
            } & {
                [key: string]: string | number | (string | number)[] | {
                    [key: string]: string | number | (string | number)[];
                };
            };
            global?: {
                image?: string;
                gpu?: boolean;
                entrypoint?: string | string[];
                env?: {
                    [key: string]: string;
                };
                work_dir?: string;
                variables?: {
                    [key: string]: string;
                };
            };
            ops: {
                /** @enum {string} */
                type: "container/run" | "container/create-volume";
                id: string;
                args: {
                    image: string;
                    aliases?: string | string[];
                    cmd?: string | string[];
                    volumes?: {
                        name: string;
                        dest: string;
                    }[];
                    expose?: number | string | {
                        __spread__: string;
                        chunked?: boolean;
                    } | {
                        port: number;
                        /** @enum {string} */
                        type?: "api" | "web" | "websocket" | "webapi" | "none";
                        health_checks?: ({
                            /** @enum {string} */
                            type: "http";
                            path: string;
                            /** @enum {string} */
                            method: "GET" | "POST" | "PUT" | "DELETE";
                            expected_status: number;
                            /** @description Construct a type with a set of properties K of type T */
                            headers?: {
                                [key: string]: string;
                            };
                            body?: unknown;
                            continuous: boolean;
                        } | {
                            /** @enum {string} */
                            type: "websocket";
                            expected_response: string;
                            continuous: boolean;
                        })[];
                    } | (number | string | {
                        __spread__: string;
                        chunked?: boolean;
                    } | {
                        port: number;
                        /** @enum {string} */
                        type?: "api" | "web" | "websocket" | "webapi" | "none";
                        health_checks?: ({
                            /** @enum {string} */
                            type: "http";
                            path: string;
                            /** @enum {string} */
                            method: "GET" | "POST" | "PUT" | "DELETE";
                            expected_status: number;
                            /** @description Construct a type with a set of properties K of type T */
                            headers?: {
                                [key: string]: string;
                            };
                            body?: unknown;
                            continuous: boolean;
                        } | {
                            /** @enum {string} */
                            type: "websocket";
                            expected_response: string;
                            continuous: boolean;
                        })[];
                    })[];
                    gpu?: boolean;
                    work_dir?: string;
                    entrypoint?: string | string[];
                    env?: {
                        [key: string]: string;
                    };
                    restart_policy?: {
                        /** @enum {string} */
                        policy: "on-failure";
                        restart_tries?: number;
                    } | ("on-failure" | "no" | "always" | "unless-stopped");
                    private?: boolean;
                    resources?: ({
                        __spread__: string;
                        chunked?: boolean;
                    } | {
                        /** @enum {string} */
                        type: "S3";
                        target: string;
                        url?: string;
                        allowWrite?: boolean;
                        files?: string[];
                        IAM?: {
                            REGION: string;
                            ACCESS_KEY_ID: string;
                            SECRET_ACCESS_KEY: string;
                        };
                    } | {
                        /** @enum {string} */
                        type: "S3";
                        target: string;
                        bucket: string;
                        url?: string;
                        allowWrite?: boolean;
                        IAM?: {
                            REGION: string;
                            ACCESS_KEY_ID: string;
                            SECRET_ACCESS_KEY: string;
                        };
                    } | {
                        /** @enum {string} */
                        type: "S3";
                        target: string;
                        buckets: {
                            url: string;
                            files?: string[];
                        }[];
                        url?: string;
                        allowWrite?: boolean;
                        IAM?: {
                            REGION: string;
                            ACCESS_KEY_ID: string;
                            SECRET_ACCESS_KEY: string;
                        };
                    } | {
                        /** @enum {string} */
                        type: "HF";
                        target: string;
                        repo: string;
                        revision?: string;
                        files?: string[];
                        accessToken?: string;
                    } | {
                        /** @enum {string} */
                        type: "Ollama";
                        model: string;
                        target?: string;
                    } | "__remove-if-empty__")[];
                    authentication?: {
                        docker?: {
                            username?: string;
                            password?: string;
                            email?: string;
                            server?: string;
                        };
                    };
                } | {
                    name: string;
                };
                results?: {
                    [key: string]: string | {
                        regex: string;
                        logType: ("stdin" | "stdout" | "stderr" | "nodeerr")[];
                    };
                };
                execution?: {
                    group?: string;
                    timeout?: number;
                    depends_on: string[];
                    stop_if_dependent_stops?: boolean;
                } | {
                    group?: string;
                    timeout?: number;
                };
            }[];
        };
        /** JobResults */
        JobResults: {
            status: string;
            startTime: number;
            endTime: number | null;
            errors?: unknown[];
            opStates: {
                providerId: string | null;
                operationId: string | null;
                group: string | null;
                status: string | null;
                startTime: number | null;
                endTime: number | null;
                exitCode: number | null;
                logs: {
                    /** @enum {string} */
                    type: "stdin" | "stdout" | "stderr" | "nodeerr";
                    log?: string;
                    timestamp?: string;
                }[];
                results?: {
                    [key: string]: string | string[];
                };
                error?: {
                    event: string;
                    message: string;
                    code?: number;
                };
                diagnostics: {
                    reason: {
                        hostShutDown: boolean;
                        jobStopped: boolean;
                        jobExpired: boolean;
                        reason?: string;
                    };
                    state?: {
                        Status: string;
                        Running: boolean;
                        Paused: boolean;
                        Restarting: boolean;
                        OOMKilled: boolean;
                        Dead: boolean;
                        Pid: number;
                        ExitCode: number;
                        Error: string;
                        StartedAt: string;
                        FinishedAt: string;
                        Health?: {
                            Status: string;
                            FailingStreak: number;
                            Log: {
                                Start: string;
                                End: string;
                                ExitCode: number;
                                Output: string;
                            }[] | null;
                        };
                        RestartCount: number;
                    };
                };
            }[];
            secrets?: {
                /** @enum {string} */
                urlmode?: "private" | "public";
            } & {
                [key: string]: {
                    [key: string]: {
                        opID: string;
                        port: string | number;
                        url: string;
                        /** @enum {string} */
                        status: "ONLINE" | "OFFLINE" | "UNKNOWN";
                    };
                } | ("private" | "public");
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
