/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { NOSANA_JOBS_PROGRAM_ADDRESS } from "../programs/index.js";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared/index.js";

export const CLOSE_ADMIN_INSTRUCTION_ACCOUNTS = {
  market: 0,
  vault: 1,
  user: 2,
  authority: 3,
  tokenProgram: 4,
} as const;

export type CloseAdminInstructionAccountName = keyof typeof CLOSE_ADMIN_INSTRUCTION_ACCOUNTS;
export const CLOSE_ADMIN_DISCRIMINATOR = new Uint8Array([
  202, 182, 185, 142, 208, 161, 145, 189,
]);

export function getCloseAdminDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CLOSE_ADMIN_DISCRIMINATOR);
}

export type CloseAdminInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountMarket extends string
        ? WritableAccount<TAccountMarket>
        : TAccountMarket,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountUser extends string
        ? WritableAccount<TAccountUser>
        : TAccountUser,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CloseAdminInstructionData = { discriminator: ReadonlyUint8Array };

export type CloseAdminInstructionDataArgs = {};

export function getCloseAdminInstructionDataEncoder(): FixedSizeEncoder<CloseAdminInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLOSE_ADMIN_DISCRIMINATOR }),
  );
}

export function getCloseAdminInstructionDataDecoder(): FixedSizeDecoder<CloseAdminInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCloseAdminInstructionDataCodec(): FixedSizeCodec<
  CloseAdminInstructionDataArgs,
  CloseAdminInstructionData
> {
  return combineCodec(
    getCloseAdminInstructionDataEncoder(),
    getCloseAdminInstructionDataDecoder(),
  );
}

export type CloseAdminInput<
  TAccountMarket extends string = string,
  TAccountVault extends string = string,
  TAccountUser extends string = string,
  TAccountAuthority extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  market: Address<TAccountMarket>;
  vault: Address<TAccountVault>;
  user: Address<TAccountUser>;
  authority: TransactionSigner<TAccountAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getCloseAdminInstruction<
  TAccountMarket extends string,
  TAccountVault extends string,
  TAccountUser extends string,
  TAccountAuthority extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
>(
  input: CloseAdminInput<
    TAccountMarket,
    TAccountVault,
    TAccountUser,
    TAccountAuthority,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CloseAdminInstruction<
  TProgramAddress,
  TAccountMarket,
  TAccountVault,
  TAccountUser,
  TAccountAuthority,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOSANA_JOBS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    market: { value: input.market ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    user: { value: input.user ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getCloseAdminInstructionDataEncoder().encode({}),
    programAddress,
  } as CloseAdminInstruction<
    TProgramAddress,
    TAccountMarket,
    TAccountVault,
    TAccountUser,
    TAccountAuthority,
    TAccountTokenProgram
  >);
}

export type ParsedCloseAdminInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    market: TAccountMetas[0];
    vault: TAccountMetas[1];
    user: TAccountMetas[2];
    authority: TAccountMetas[3];
    tokenProgram: TAccountMetas[4];
  };
  data: CloseAdminInstructionData;
};

export function parseCloseAdminInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCloseAdminInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      market: getNextAccount(),
      vault: getNextAccount(),
      user: getNextAccount(),
      authority: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getCloseAdminInstructionDataDecoder().decode(instruction.data),
  };
}
