/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/validate-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postAuthValidate-session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/validate-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postAuthValidate-api-key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-message/external": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign message for external service authentication
         * @description Sign message for external service authentication
         */
        post: operations["postAuthSign-messageExternal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get API Keys
         * @description Get all API keys for the authenticated user
         */
        get: operations["getApi-keys"];
        put?: never;
        /**
         * Create API Key
         * @description Create a new API key for the authenticated user
         */
        post: operations["postApi-keys"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get API Key
         * @description Get a specific API key by ID
         */
        get: operations["getApi-keysById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{id}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update API Key
         * @description Update an API key (name or status)
         */
        post: operations["postApi-keysByIdUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete API Key
         * @description Delete an API key
         */
        post: operations["postApi-keysByIdDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postCreditsClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/invitations/{token}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postCreditsInvitationsByTokenClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postCreditsRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/request/eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCreditsRequestEligibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCreditsBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCreditsInvitationsByToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/admin/request/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCreditsAdminRequestConfig"];
        put?: never;
        post: operations["postCreditsAdminRequestConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/admin/codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCreditsAdminCodes"];
        put?: never;
        post: operations["postCreditsAdminCodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCreditsAdminAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/admin/accounts/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCreditsAdminAccountsByUserId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/admin/codes/{code}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postCreditsAdminCodesByCodeUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/admin/codes/{code}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postCreditsAdminCodesByCodeDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/admin/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postCreditsAdminInvitations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/admin/invitations/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postCreditsAdminInvitationsBulk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/admin/user-credit-alert-threshold-usd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCreditsAdminUser-credit-alert-threshold-usd"];
        put?: never;
        post: operations["postCreditsAdminUser-credit-alert-threshold-usd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/request/amount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the free credit request amount */
        get: operations["getCreditsRequestAmount"];
        put?: never;
        /** Set the free credit request amount */
        post: operations["postCreditsRequestAmount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/accounts/{userId}/zero": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Zero out assigned credits for a user */
        post: operations["postCreditsAccountsByUserIdZero"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracker/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTracker"];
        put?: never;
        post: operations["postTracker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracker/{name}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postTrackerByNameUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracker/{name}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postTrackerByNameDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/grouped": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTemplatesGrouped"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTemplatesById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{id}/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTemplatesByIdByVariantId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a job using credits
         * @description Create a job using credits. Supports both JWT tokens (Bearer <jwt>) and API keys (Bearer nos_...)
         */
        post: operations["postJobsList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{address}/extend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extend a job using credits
         * @description Extend a job using credits. Supports both JWT tokens (Bearer <jwt>) and API keys (Bearer nos_...)
         */
        post: operations["postJobsByAddressExtend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{address}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop a job paid with credits
         * @description Stop a job paid with credits. Supports both JWT tokens (Bearer <jwt>) and API keys (Bearer nos_...)
         */
        post: operations["postJobsByAddressStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/newsletter/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Subscribe To Newsletter
         * @description Subscribe an email address to the newsletter list
         */
        post: operations["postNewsletterSubscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "postAuthValidate-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    cookieHeader?: string;
                };
                "multipart/form-data": {
                    cookieHeader?: string;
                };
                "text/plain": {
                    cookieHeader?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        valid: boolean;
                        user?: {
                            id: string;
                            supertokensUserId: (string | null) | null;
                            legacyUserId: (string | null) | null;
                            email: string;
                            name: (string | null) | null;
                            provider: (string | null) | null;
                            providerUsername: (string | null) | null;
                            generatedAddress: string;
                            authenticationHeader: string;
                            systemApiKey: string;
                            created_at: ((Record<string, never> | string | number) | null) | null;
                        };
                        session?: {
                            handle?: string;
                            expiresAt?: string;
                        };
                    };
                    "multipart/form-data": {
                        valid: boolean;
                        user?: {
                            id: string;
                            supertokensUserId: (string | null) | null;
                            legacyUserId: (string | null) | null;
                            email: string;
                            name: (string | null) | null;
                            provider: (string | null) | null;
                            providerUsername: (string | null) | null;
                            generatedAddress: string;
                            authenticationHeader: string;
                            systemApiKey: string;
                            created_at: ((Record<string, never> | string | number) | null) | null;
                        };
                        session?: {
                            handle?: string;
                            expiresAt?: string;
                        };
                    };
                    "text/plain": {
                        valid: boolean;
                        user?: {
                            id: string;
                            supertokensUserId: (string | null) | null;
                            legacyUserId: (string | null) | null;
                            email: string;
                            name: (string | null) | null;
                            provider: (string | null) | null;
                            providerUsername: (string | null) | null;
                            generatedAddress: string;
                            authenticationHeader: string;
                            systemApiKey: string;
                            created_at: ((Record<string, never> | string | number) | null) | null;
                        };
                        session?: {
                            handle?: string;
                            expiresAt?: string;
                        };
                    };
                };
            };
        };
    };
    "postAuthValidate-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    apiKey: string;
                };
                "multipart/form-data": {
                    apiKey: string;
                };
                "text/plain": {
                    apiKey: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        valid: boolean;
                        user?: {
                            id: string;
                            legacyUserId: (string | null) | null;
                            email: string;
                            name: (string | null) | null;
                            provider: (string | null) | null;
                            providerUsername: (string | null) | null;
                            generatedAddress: string;
                            authenticationHeader: string;
                            systemApiKey: string;
                            created_at: ((Record<string, never> | string | number) | null) | null;
                        };
                        apiKeyId?: string;
                    };
                    "multipart/form-data": {
                        valid: boolean;
                        user?: {
                            id: string;
                            legacyUserId: (string | null) | null;
                            email: string;
                            name: (string | null) | null;
                            provider: (string | null) | null;
                            providerUsername: (string | null) | null;
                            generatedAddress: string;
                            authenticationHeader: string;
                            systemApiKey: string;
                            created_at: ((Record<string, never> | string | number) | null) | null;
                        };
                        apiKeyId?: string;
                    };
                    "text/plain": {
                        valid: boolean;
                        user?: {
                            id: string;
                            legacyUserId: (string | null) | null;
                            email: string;
                            name: (string | null) | null;
                            provider: (string | null) | null;
                            providerUsername: (string | null) | null;
                            generatedAddress: string;
                            authenticationHeader: string;
                            systemApiKey: string;
                            created_at: ((Record<string, never> | string | number) | null) | null;
                        };
                        apiKeyId?: string;
                    };
                };
            };
        };
    };
    "postAuthSign-messageExternal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The message to be signed with the user's private key */
                    message: string;
                    includeTime?: boolean;
                };
                "multipart/form-data": {
                    /** @description The message to be signed with the user's private key */
                    message: string;
                    includeTime?: boolean;
                };
                "text/plain": {
                    /** @description The message to be signed with the user's private key */
                    message: string;
                    includeTime?: boolean;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description The signed message in base58 format */
                        signature: string;
                        /** @description The original message that was signed */
                        message: string;
                        /** @description The address of the user whose private key should be used for signing */
                        userAddress: string;
                        /** @description Unix ms when the signature was created; present when includeTime was true */
                        timestamp?: number;
                    };
                    "multipart/form-data": {
                        /** @description The signed message in base58 format */
                        signature: string;
                        /** @description The original message that was signed */
                        message: string;
                        /** @description The address of the user whose private key should be used for signing */
                        userAddress: string;
                        /** @description Unix ms when the signature was created; present when includeTime was true */
                        timestamp?: number;
                    };
                    "text/plain": {
                        /** @description The signed message in base58 format */
                        signature: string;
                        /** @description The original message that was signed */
                        message: string;
                        /** @description The address of the user whose private key should be used for signing */
                        userAddress: string;
                        /** @description Unix ms when the signature was created; present when includeTime was true */
                        timestamp?: number;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                        message: string;
                    };
                    "multipart/form-data": {
                        name: string;
                        message: string;
                    };
                    "text/plain": {
                        name: string;
                        message: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                        message: string;
                    };
                    "multipart/form-data": {
                        name: string;
                        message: string;
                    };
                    "text/plain": {
                        name: string;
                        message: string;
                    };
                };
            };
        };
    };
    "getApi-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        keys: {
                            id: string;
                            name: string;
                            /** @description Full API key */
                            key: string;
                            status: string;
                            lastUsedAt: (string | null) | null;
                            expiresAt: (string | null) | null;
                            createdAt: string;
                            updatedAt: string;
                        }[];
                        total: number;
                    };
                    "multipart/form-data": {
                        keys: {
                            id: string;
                            name: string;
                            /** @description Full API key */
                            key: string;
                            status: string;
                            lastUsedAt: (string | null) | null;
                            expiresAt: (string | null) | null;
                            createdAt: string;
                            updatedAt: string;
                        }[];
                        total: number;
                    };
                    "text/plain": {
                        keys: {
                            id: string;
                            name: string;
                            /** @description Full API key */
                            key: string;
                            status: string;
                            lastUsedAt: (string | null) | null;
                            expiresAt: (string | null) | null;
                            createdAt: string;
                            updatedAt: string;
                        }[];
                        total: number;
                    };
                };
            };
        };
    };
    "postApi-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description A descriptive name for the API key. */
                    name: string;
                    /** @description Key expiration time in seconds. If not provided, key never expires. */
                    expiresIn?: number;
                };
                "multipart/form-data": {
                    /** @description A descriptive name for the API key. */
                    name: string;
                    /** @description Key expiration time in seconds. If not provided, key never expires. */
                    expiresIn?: number;
                };
                "text/plain": {
                    /** @description A descriptive name for the API key. */
                    name: string;
                    /** @description Key expiration time in seconds. If not provided, key never expires. */
                    expiresIn?: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description The full API key. */
                        key: string;
                        id: string;
                        name: string;
                        status: string;
                        expiresAt: (string | null) | null;
                        createdAt: string;
                    };
                    "multipart/form-data": {
                        /** @description The full API key. */
                        key: string;
                        id: string;
                        name: string;
                        status: string;
                        expiresAt: (string | null) | null;
                        createdAt: string;
                    };
                    "text/plain": {
                        /** @description The full API key. */
                        key: string;
                        id: string;
                        name: string;
                        status: string;
                        expiresAt: (string | null) | null;
                        createdAt: string;
                    };
                };
            };
        };
    };
    "getApi-keysById": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        /** @description Full API key */
                        key: string;
                        status: string;
                        lastUsedAt: (string | null) | null;
                        expiresAt: (string | null) | null;
                        createdAt: string;
                        updatedAt: string;
                    };
                    "multipart/form-data": {
                        id: string;
                        name: string;
                        /** @description Full API key */
                        key: string;
                        status: string;
                        lastUsedAt: (string | null) | null;
                        expiresAt: (string | null) | null;
                        createdAt: string;
                        updatedAt: string;
                    };
                    "text/plain": {
                        id: string;
                        name: string;
                        /** @description Full API key */
                        key: string;
                        status: string;
                        lastUsedAt: (string | null) | null;
                        expiresAt: (string | null) | null;
                        createdAt: string;
                        updatedAt: string;
                    };
                };
            };
        };
    };
    "postApi-keysByIdUpdate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Update the key name. */
                    name?: string;
                    /** @description Update the key status. */
                    status?: "active" | "disabled";
                };
                "multipart/form-data": {
                    /** @description Update the key name. */
                    name?: string;
                    /** @description Update the key status. */
                    status?: "active" | "disabled";
                };
                "text/plain": {
                    /** @description Update the key name. */
                    name?: string;
                    /** @description Update the key status. */
                    status?: "active" | "disabled";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        /** @description Full API key */
                        key: string;
                        status: string;
                        lastUsedAt: (string | null) | null;
                        expiresAt: (string | null) | null;
                        createdAt: string;
                        updatedAt: string;
                    };
                    "multipart/form-data": {
                        id: string;
                        name: string;
                        /** @description Full API key */
                        key: string;
                        status: string;
                        lastUsedAt: (string | null) | null;
                        expiresAt: (string | null) | null;
                        createdAt: string;
                        updatedAt: string;
                    };
                    "text/plain": {
                        id: string;
                        name: string;
                        /** @description Full API key */
                        key: string;
                        status: string;
                        lastUsedAt: (string | null) | null;
                        expiresAt: (string | null) | null;
                        createdAt: string;
                        updatedAt: string;
                    };
                };
            };
        };
    };
    "postApi-keysByIdDelete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                    "multipart/form-data": {
                        success: boolean;
                    };
                    "text/plain": {
                        success: boolean;
                    };
                };
            };
        };
    };
    postCreditsClaim: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The credit code to claim. */
                    code: string;
                };
                "multipart/form-data": {
                    /** @description The credit code to claim. */
                    code: string;
                };
                "text/plain": {
                    /** @description The credit code to claim. */
                    code: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postCreditsInvitationsByTokenClaim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postCreditsRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCreditsRequestEligibility: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCreditsBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCreditsInvitationsByToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCreditsAdminRequestConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postCreditsAdminRequestConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    enabled: boolean;
                };
                "multipart/form-data": {
                    enabled: boolean;
                };
                "text/plain": {
                    enabled: boolean;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCreditsAdminCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postCreditsAdminCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    creditsAmount: number;
                    expirationDate?: string;
                    restrictedEmail?: string;
                    restrictedAccountName?: string;
                };
                "multipart/form-data": {
                    creditsAmount: number;
                    expirationDate?: string;
                    restrictedEmail?: string;
                    restrictedAccountName?: string;
                };
                "text/plain": {
                    creditsAmount: number;
                    expirationDate?: string;
                    restrictedEmail?: string;
                    restrictedAccountName?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCreditsAdminAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCreditsAdminAccountsByUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postCreditsAdminCodesByCodeUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    creditsAmount?: number;
                    expirationDate?: string | null;
                    restrictedEmail?: string | null;
                    restrictedAccountName?: string | null;
                };
                "multipart/form-data": {
                    creditsAmount?: number;
                    expirationDate?: string | null;
                    restrictedEmail?: string | null;
                    restrictedAccountName?: string | null;
                };
                "text/plain": {
                    creditsAmount?: number;
                    expirationDate?: string | null;
                    restrictedEmail?: string | null;
                    restrictedAccountName?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postCreditsAdminCodesByCodeDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postCreditsAdminInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    creditsAmount: number;
                    expirationDate?: string;
                    restrictedEmail?: string;
                    restrictedAccountName?: string;
                };
                "multipart/form-data": {
                    creditsAmount: number;
                    expirationDate?: string;
                    restrictedEmail?: string;
                    restrictedAccountName?: string;
                };
                "text/plain": {
                    creditsAmount: number;
                    expirationDate?: string;
                    restrictedEmail?: string;
                    restrictedAccountName?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postCreditsAdminInvitationsBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    creditsAmount: number;
                    count: number;
                    expirationDate?: string | null;
                };
                "multipart/form-data": {
                    creditsAmount: number;
                    count: number;
                    expirationDate?: string | null;
                };
                "text/plain": {
                    creditsAmount: number;
                    count: number;
                    expirationDate?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "getCreditsAdminUser-credit-alert-threshold-usd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "postCreditsAdminUser-credit-alert-threshold-usd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: string;
                };
                "multipart/form-data": {
                    value: string;
                };
                "text/plain": {
                    value: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCreditsRequestAmount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postCreditsRequestAmount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Amount in millicents (e.g. 50000 = $50) */
                    amount: number;
                };
                "multipart/form-data": {
                    /** @description Amount in millicents (e.g. 50000 = $50) */
                    amount: number;
                };
                "text/plain": {
                    /** @description Amount in millicents (e.g. 50000 = $50) */
                    amount: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postCreditsAccountsByUserIdZero: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTracker: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postTracker: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    wallet: string;
                    minimumUsd: number;
                    minimumSol: number;
                };
                "multipart/form-data": {
                    name: string;
                    wallet: string;
                    minimumUsd: number;
                    minimumSol: number;
                };
                "text/plain": {
                    name: string;
                    wallet: string;
                    minimumUsd: number;
                    minimumSol: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postTrackerByNameUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    wallet?: string;
                    minimumUsd?: number;
                    minimumSol?: number;
                };
                "multipart/form-data": {
                    wallet?: string;
                    minimumUsd?: number;
                    minimumSol?: number;
                };
                "text/plain": {
                    wallet?: string;
                    minimumUsd?: number;
                    minimumSol?: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postTrackerByNameDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTemplatesGrouped: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTemplatesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTemplatesByIdByVariantId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                variantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postJobsList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description IPFS hash of the job definition */
                    ipfsHash: string;
                    /** @description Market address */
                    market: string;
                    /** @description Job timeout in seconds (default: 3600) */
                    timeout?: number;
                    /** @description Optional node address */
                    node?: string;
                };
                "multipart/form-data": {
                    /** @description IPFS hash of the job definition */
                    ipfsHash: string;
                    /** @description Market address */
                    market: string;
                    /** @description Job timeout in seconds (default: 3600) */
                    timeout?: number;
                    /** @description Optional node address */
                    node?: string;
                };
                "text/plain": {
                    /** @description IPFS hash of the job definition */
                    ipfsHash: string;
                    /** @description Market address */
                    market: string;
                    /** @description Job timeout in seconds (default: 3600) */
                    timeout?: number;
                    /** @description Optional node address */
                    node?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tx: string;
                        job: string;
                        run: string;
                        credits: {
                            costUSD: number;
                            creditsUsed: number;
                            reservationId: string;
                            project: string;
                        };
                    };
                    "multipart/form-data": {
                        tx: string;
                        job: string;
                        run: string;
                        credits: {
                            costUSD: number;
                            creditsUsed: number;
                            reservationId: string;
                            project: string;
                        };
                    };
                    "text/plain": {
                        tx: string;
                        job: string;
                        run: string;
                        credits: {
                            costUSD: number;
                            creditsUsed: number;
                            reservationId: string;
                            project: string;
                        };
                    };
                };
            };
        };
    };
    postJobsByAddressExtend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job address */
                address: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Number of seconds to extend the job */
                    seconds: string | number;
                };
                "multipart/form-data": {
                    /** @description Number of seconds to extend the job */
                    seconds: string | number;
                };
                "text/plain": {
                    /** @description Number of seconds to extend the job */
                    seconds: string | number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tx: string;
                        job: string;
                        credits: {
                            costUSD: number;
                            creditsUsed: number;
                            reservationId: string;
                        };
                    };
                    "multipart/form-data": {
                        tx: string;
                        job: string;
                        credits: {
                            costUSD: number;
                            creditsUsed: number;
                            reservationId: string;
                        };
                    };
                    "text/plain": {
                        tx: string;
                        job: string;
                        credits: {
                            costUSD: number;
                            creditsUsed: number;
                            reservationId: string;
                        };
                    };
                };
            };
        };
    };
    postJobsByAddressStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job address */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tx: string;
                        job: string;
                        delisted: boolean;
                    };
                    "multipart/form-data": {
                        tx: string;
                        job: string;
                        delisted: boolean;
                    };
                    "text/plain": {
                        tx: string;
                        job: string;
                        delisted: boolean;
                    };
                };
            };
        };
    };
    postNewsletterSubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @description Email address to subscribe to the newsletter.
                     */
                    email: string;
                };
                "multipart/form-data": {
                    /**
                     * Format: email
                     * @description Email address to subscribe to the newsletter.
                     */
                    email: string;
                };
                "text/plain": {
                    /**
                     * Format: email
                     * @description Email address to subscribe to the newsletter.
                     */
                    email: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                    "multipart/form-data": {
                        success: boolean;
                    };
                    "text/plain": {
                        success: boolean;
                    };
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
