/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';

export const JOB_ACCOUNT_DISCRIMINATOR = new Uint8Array([
  91, 16, 162, 5, 45, 210, 125, 65,
]);

export function getJobAccountDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(JOB_ACCOUNT_DISCRIMINATOR);
}

export type JobAccount = {
  discriminator: ReadonlyUint8Array;
  ipfsJob: ReadonlyUint8Array;
  ipfsResult: ReadonlyUint8Array;
  market: Address;
  node: Address;
  payer: Address;
  price: bigint;
  project: Address;
  state: number;
  timeEnd: bigint;
  timeStart: bigint;
  timeout: bigint;
};

export type JobAccountArgs = {
  ipfsJob: ReadonlyUint8Array;
  ipfsResult: ReadonlyUint8Array;
  market: Address;
  node: Address;
  payer: Address;
  price: number | bigint;
  project: Address;
  state: number;
  timeEnd: number | bigint;
  timeStart: number | bigint;
  timeout: number | bigint;
};

export function getJobAccountEncoder(): Encoder<JobAccountArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['ipfsJob', fixEncoderSize(getBytesEncoder(), 32)],
      ['ipfsResult', fixEncoderSize(getBytesEncoder(), 32)],
      ['market', getAddressEncoder()],
      ['node', getAddressEncoder()],
      ['payer', getAddressEncoder()],
      ['price', getU64Encoder()],
      ['project', getAddressEncoder()],
      ['state', getU8Encoder()],
      ['timeEnd', getI64Encoder()],
      ['timeStart', getI64Encoder()],
      ['timeout', getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: JOB_ACCOUNT_DISCRIMINATOR })
  );
}

export function getJobAccountDecoder(): Decoder<JobAccount> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['ipfsJob', fixDecoderSize(getBytesDecoder(), 32)],
    ['ipfsResult', fixDecoderSize(getBytesDecoder(), 32)],
    ['market', getAddressDecoder()],
    ['node', getAddressDecoder()],
    ['payer', getAddressDecoder()],
    ['price', getU64Decoder()],
    ['project', getAddressDecoder()],
    ['state', getU8Decoder()],
    ['timeEnd', getI64Decoder()],
    ['timeStart', getI64Decoder()],
    ['timeout', getI64Decoder()],
  ]);
}

export function getJobAccountCodec(): Codec<JobAccountArgs, JobAccount> {
  return combineCodec(getJobAccountEncoder(), getJobAccountDecoder());
}

export function decodeJobAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<JobAccount, TAddress>;
export function decodeJobAccount<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<JobAccount, TAddress>;
export function decodeJobAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<JobAccount, TAddress> | MaybeAccount<JobAccount, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getJobAccountDecoder()
  );
}

export async function fetchJobAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<JobAccount, TAddress>> {
  const maybeAccount = await fetchMaybeJobAccount(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeJobAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<JobAccount, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeJobAccount(maybeAccount);
}

export async function fetchAllJobAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<JobAccount>[]> {
  const maybeAccounts = await fetchAllMaybeJobAccount(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeJobAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<JobAccount>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeJobAccount(maybeAccount));
}

export function getJobAccountSize(): number {
  return 233;
}
