/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';

export const SETTINGS_ACCOUNT_DISCRIMINATOR = new Uint8Array([
  63, 89, 203, 155, 76, 237, 115, 58,
]);

export function getSettingsAccountDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SETTINGS_ACCOUNT_DISCRIMINATOR
  );
}

export type SettingsAccount = {
  discriminator: ReadonlyUint8Array;
  authority: Address;
  tokenAccount: Address;
};

export type SettingsAccountArgs = { authority: Address; tokenAccount: Address };

/** Gets the encoder for {@link SettingsAccountArgs} account data. */
export function getSettingsAccountEncoder(): FixedSizeEncoder<SettingsAccountArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['authority', getAddressEncoder()],
      ['tokenAccount', getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: SETTINGS_ACCOUNT_DISCRIMINATOR })
  );
}

/** Gets the decoder for {@link SettingsAccount} account data. */
export function getSettingsAccountDecoder(): FixedSizeDecoder<SettingsAccount> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['authority', getAddressDecoder()],
    ['tokenAccount', getAddressDecoder()],
  ]);
}

/** Gets the codec for {@link SettingsAccount} account data. */
export function getSettingsAccountCodec(): FixedSizeCodec<
  SettingsAccountArgs,
  SettingsAccount
> {
  return combineCodec(getSettingsAccountEncoder(), getSettingsAccountDecoder());
}

export function decodeSettingsAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<SettingsAccount, TAddress>;
export function decodeSettingsAccount<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<SettingsAccount, TAddress>;
export function decodeSettingsAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
):
  | Account<SettingsAccount, TAddress>
  | MaybeAccount<SettingsAccount, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getSettingsAccountDecoder()
  );
}

export async function fetchSettingsAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<SettingsAccount, TAddress>> {
  const maybeAccount = await fetchMaybeSettingsAccount(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeSettingsAccount<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<SettingsAccount, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeSettingsAccount(maybeAccount);
}

export async function fetchAllSettingsAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<SettingsAccount>[]> {
  const maybeAccounts = await fetchAllMaybeSettingsAccount(
    rpc,
    addresses,
    config
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeSettingsAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<SettingsAccount>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeSettingsAccount(maybeAccount)
  );
}

export function getSettingsAccountSize(): number {
  return 72;
}
