/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';

export const STAKE_ACCOUNT_DISCRIMINATOR = new Uint8Array([
  80, 158, 67, 124, 50, 189, 192, 255,
]);

export function getStakeAccountDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    STAKE_ACCOUNT_DISCRIMINATOR
  );
}

export type StakeAccount = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
  authority: Address;
  duration: bigint;
  timeUnstake: bigint;
  vault: Address;
  vaultBump: number;
  xnos: bigint;
};

export type StakeAccountArgs = {
  amount: number | bigint;
  authority: Address;
  duration: number | bigint;
  timeUnstake: number | bigint;
  vault: Address;
  vaultBump: number;
  xnos: number | bigint;
};

export function getStakeAccountEncoder(): Encoder<StakeAccountArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['amount', getU64Encoder()],
      ['authority', getAddressEncoder()],
      ['duration', getU64Encoder()],
      ['timeUnstake', getI64Encoder()],
      ['vault', getAddressEncoder()],
      ['vaultBump', getU8Encoder()],
      ['xnos', getU128Encoder()],
    ]),
    (value) => ({ ...value, discriminator: STAKE_ACCOUNT_DISCRIMINATOR })
  );
}

export function getStakeAccountDecoder(): Decoder<StakeAccount> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['amount', getU64Decoder()],
    ['authority', getAddressDecoder()],
    ['duration', getU64Decoder()],
    ['timeUnstake', getI64Decoder()],
    ['vault', getAddressDecoder()],
    ['vaultBump', getU8Decoder()],
    ['xnos', getU128Decoder()],
  ]);
}

export function getStakeAccountCodec(): Codec<StakeAccountArgs, StakeAccount> {
  return combineCodec(getStakeAccountEncoder(), getStakeAccountDecoder());
}

export function decodeStakeAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<StakeAccount, TAddress>;
export function decodeStakeAccount<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<StakeAccount, TAddress>;
export function decodeStakeAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<StakeAccount, TAddress> | MaybeAccount<StakeAccount, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getStakeAccountDecoder()
  );
}

export async function fetchStakeAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<StakeAccount, TAddress>> {
  const maybeAccount = await fetchMaybeStakeAccount(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeStakeAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<StakeAccount, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeStakeAccount(maybeAccount);
}

export async function fetchAllStakeAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<StakeAccount>[]> {
  const maybeAccounts = await fetchAllMaybeStakeAccount(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeStakeAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<StakeAccount>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeStakeAccount(maybeAccount));
}

export function getStakeAccountSize(): number {
  return 113;
}
