/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

/** The `JobType` describes the type of any job. */
export enum JobType {
  Default,
  Small,
  Medium,
  Large,
  Gpu,
  Unknown,
}

export type JobTypeArgs = JobType;

export function getJobTypeEncoder(): Encoder<JobTypeArgs> {
  return getEnumEncoder(JobType);
}

export function getJobTypeDecoder(): Decoder<JobType> {
  return getEnumDecoder(JobType);
}

export function getJobTypeCodec(): Codec<JobTypeArgs, JobType> {
  return combineCodec(getJobTypeEncoder(), getJobTypeDecoder());
}
