/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

/** The `QueueType` describes the type of queue */
export enum QueueType {
  Job,
  Node,
  Empty,
}

export type QueueTypeArgs = QueueType;

export function getQueueTypeEncoder(): Encoder<QueueTypeArgs> {
  return getEnumEncoder(QueueType);
}

export function getQueueTypeDecoder(): Decoder<QueueType> {
  return getEnumDecoder(QueueType);
}

export function getQueueTypeCodec(): Codec<QueueTypeArgs, QueueType> {
  return combineCodec(getQueueTypeEncoder(), getQueueTypeDecoder());
}
