stages:
  - test
  - build

include:
  - local: .gitlab/ci/common.yml

kit:npm format:
  stage: test
  script:
    - pnpm install --frozen-lockfile
    - pnpm --filter @nosana/kit run format
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

kit:npm lint:
  stage: test
  script:
    - pnpm install --frozen-lockfile
    - pnpm --filter @nosana/kit run lint
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

kit:npm test:
  stage: test
  script:
    - pnpm install --frozen-lockfile
    - pnpm --filter @nosana/kit run build:with-deps
    - pnpm --filter @nosana/kit run test
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

kit:npm test:scenario:
  stage: test
  image: docker:24.0.7
  before_script: []
  services:
    - name: docker:24.0.7-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_TLS_VERIFY: "0"
    DOCKER_CERT_PATH: ""
  script:
    - export DOCKER_TLS_CERTDIR=
    - export DOCKER_TLS_VERIFY=
    - export DOCKER_CERT_PATH=
    - apk add --no-cache nodejs npm
    - npm install -g pnpm@10.28.0
    - pnpm install --frozen-lockfile
    - pnpm --filter @nosana/scenario... run build
    - pnpm --filter @nosana/kit run test:scenario:localnet
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH