stages:
  - test
  - build

include:
  - local: .gitlab/ci/common.yml

kit:npm format:
  stage: test
  script:
    - pnpm install --frozen-lockfile
    - pnpm --filter @nosana/kit run format
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

kit:npm lint:
  stage: test
  script:
    - pnpm install --frozen-lockfile
    - pnpm --filter @nosana/kit run lint
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

kit:npm test:
  stage: test
  script:
    - pnpm install --frozen-lockfile
    - pnpm --filter @nosana/kit run build:with-deps
    - pnpm --filter @nosana/kit run test
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
