/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { NOSANA_STAKING_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const EXTEND_DISCRIMINATOR = new Uint8Array([
  228, 127, 0, 1, 227, 154, 54, 168,
]);

export function getExtendDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(EXTEND_DISCRIMINATOR);
}

export type ExtendInstruction<
  TProgram extends string = typeof NOSANA_STAKING_PROGRAM_ADDRESS,
  TAccountStake extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountStake extends string
        ? WritableAccount<TAccountStake>
        : TAccountStake,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type ExtendInstructionData = {
  discriminator: ReadonlyUint8Array;
  duration: bigint;
};

export type ExtendInstructionDataArgs = { duration: number | bigint };

export function getExtendInstructionDataEncoder(): Encoder<ExtendInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['duration', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: EXTEND_DISCRIMINATOR })
  );
}

export function getExtendInstructionDataDecoder(): Decoder<ExtendInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['duration', getU64Decoder()],
  ]);
}

export function getExtendInstructionDataCodec(): Codec<
  ExtendInstructionDataArgs,
  ExtendInstructionData
> {
  return combineCodec(
    getExtendInstructionDataEncoder(),
    getExtendInstructionDataDecoder()
  );
}

export type ExtendInput<
  TAccountStake extends string = string,
  TAccountAuthority extends string = string,
> = {
  stake: Address<TAccountStake>;
  authority: TransactionSigner<TAccountAuthority>;
  duration: ExtendInstructionDataArgs['duration'];
};

export function getExtendInstruction<
  TAccountStake extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof NOSANA_STAKING_PROGRAM_ADDRESS,
>(
  input: ExtendInput<TAccountStake, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress }
): ExtendInstruction<TProgramAddress, TAccountStake, TAccountAuthority> {
  // Program address.
  const programAddress =
    config?.programAddress ?? NOSANA_STAKING_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    stake: { value: input.stake ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.stake),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getExtendInstructionDataEncoder().encode(
      args as ExtendInstructionDataArgs
    ),
  } as ExtendInstruction<TProgramAddress, TAccountStake, TAccountAuthority>;

  return instruction;
}

export type ParsedExtendInstruction<
  TProgram extends string = typeof NOSANA_STAKING_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    stake: TAccountMetas[0];
    authority: TAccountMetas[1];
  };
  data: ExtendInstructionData;
};

export function parseExtendInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedExtendInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      stake: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getExtendInstructionDataDecoder().decode(instruction.data),
  };
}
