/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { NOSANA_STAKING_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const RESTAKE_DISCRIMINATOR = new Uint8Array([
  97, 161, 241, 167, 6, 32, 213, 53,
]);

export function getRestakeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(RESTAKE_DISCRIMINATOR);
}

export type RestakeInstruction<
  TProgram extends string = typeof NOSANA_STAKING_PROGRAM_ADDRESS,
  TAccountVault extends string | IAccountMeta<string> = string,
  TAccountStake extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountStake extends string
        ? WritableAccount<TAccountStake>
        : TAccountStake,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type RestakeInstructionData = { discriminator: ReadonlyUint8Array };

export type RestakeInstructionDataArgs = {};

export function getRestakeInstructionDataEncoder(): Encoder<RestakeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: RESTAKE_DISCRIMINATOR })
  );
}

export function getRestakeInstructionDataDecoder(): Decoder<RestakeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getRestakeInstructionDataCodec(): Codec<
  RestakeInstructionDataArgs,
  RestakeInstructionData
> {
  return combineCodec(
    getRestakeInstructionDataEncoder(),
    getRestakeInstructionDataDecoder()
  );
}

export type RestakeInput<
  TAccountVault extends string = string,
  TAccountStake extends string = string,
  TAccountAuthority extends string = string,
> = {
  vault: Address<TAccountVault>;
  stake: Address<TAccountStake>;
  authority: TransactionSigner<TAccountAuthority>;
};

export function getRestakeInstruction<
  TAccountVault extends string,
  TAccountStake extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof NOSANA_STAKING_PROGRAM_ADDRESS,
>(
  input: RestakeInput<TAccountVault, TAccountStake, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress }
): RestakeInstruction<
  TProgramAddress,
  TAccountVault,
  TAccountStake,
  TAccountAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? NOSANA_STAKING_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: true },
    stake: { value: input.stake ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.stake),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getRestakeInstructionDataEncoder().encode({}),
  } as RestakeInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountStake,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedRestakeInstruction<
  TProgram extends string = typeof NOSANA_STAKING_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vault: TAccountMetas[0];
    stake: TAccountMetas[1];
    authority: TAccountMetas[2];
  };
  data: RestakeInstructionData;
};

export function parseRestakeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedRestakeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      vault: getNextAccount(),
      stake: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getRestakeInstructionDataDecoder().decode(instruction.data),
  };
}
