/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { NOSANA_STAKING_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const SLASH_DISCRIMINATOR = new Uint8Array([
  204, 141, 18, 161, 8, 177, 92, 142,
]);

export function getSlashDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(SLASH_DISCRIMINATOR);
}

export type SlashInstruction<
  TProgram extends string = typeof NOSANA_STAKING_PROGRAM_ADDRESS,
  TAccountVault extends string | IAccountMeta<string> = string,
  TAccountStake extends string | IAccountMeta<string> = string,
  TAccountTokenAccount extends string | IAccountMeta<string> = string,
  TAccountSettings extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountStake extends string
        ? WritableAccount<TAccountStake>
        : TAccountStake,
      TAccountTokenAccount extends string
        ? WritableAccount<TAccountTokenAccount>
        : TAccountTokenAccount,
      TAccountSettings extends string
        ? ReadonlyAccount<TAccountSettings>
        : TAccountSettings,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type SlashInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type SlashInstructionDataArgs = { amount: number | bigint };

export function getSlashInstructionDataEncoder(): Encoder<SlashInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['amount', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SLASH_DISCRIMINATOR })
  );
}

export function getSlashInstructionDataDecoder(): Decoder<SlashInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['amount', getU64Decoder()],
  ]);
}

export function getSlashInstructionDataCodec(): Codec<
  SlashInstructionDataArgs,
  SlashInstructionData
> {
  return combineCodec(
    getSlashInstructionDataEncoder(),
    getSlashInstructionDataDecoder()
  );
}

export type SlashInput<
  TAccountVault extends string = string,
  TAccountStake extends string = string,
  TAccountTokenAccount extends string = string,
  TAccountSettings extends string = string,
  TAccountAuthority extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  vault: Address<TAccountVault>;
  stake: Address<TAccountStake>;
  tokenAccount: Address<TAccountTokenAccount>;
  settings: Address<TAccountSettings>;
  authority: TransactionSigner<TAccountAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
  amount: SlashInstructionDataArgs['amount'];
};

export function getSlashInstruction<
  TAccountVault extends string,
  TAccountStake extends string,
  TAccountTokenAccount extends string,
  TAccountSettings extends string,
  TAccountAuthority extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof NOSANA_STAKING_PROGRAM_ADDRESS,
>(
  input: SlashInput<
    TAccountVault,
    TAccountStake,
    TAccountTokenAccount,
    TAccountSettings,
    TAccountAuthority,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): SlashInstruction<
  TProgramAddress,
  TAccountVault,
  TAccountStake,
  TAccountTokenAccount,
  TAccountSettings,
  TAccountAuthority,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? NOSANA_STAKING_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vault: { value: input.vault ?? null, isWritable: true },
    stake: { value: input.stake ?? null, isWritable: true },
    tokenAccount: { value: input.tokenAccount ?? null, isWritable: true },
    settings: { value: input.settings ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.stake),
      getAccountMeta(accounts.tokenAccount),
      getAccountMeta(accounts.settings),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getSlashInstructionDataEncoder().encode(
      args as SlashInstructionDataArgs
    ),
  } as SlashInstruction<
    TProgramAddress,
    TAccountVault,
    TAccountStake,
    TAccountTokenAccount,
    TAccountSettings,
    TAccountAuthority,
    TAccountTokenProgram
  >;

  return instruction;
}

export type ParsedSlashInstruction<
  TProgram extends string = typeof NOSANA_STAKING_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vault: TAccountMetas[0];
    stake: TAccountMetas[1];
    tokenAccount: TAccountMetas[2];
    settings: TAccountMetas[3];
    authority: TAccountMetas[4];
    tokenProgram: TAccountMetas[5];
  };
  data: SlashInstructionData;
};

export function parseSlashInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedSlashInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      vault: getNextAccount(),
      stake: getNextAccount(),
      tokenAccount: getNextAccount(),
      settings: getNextAccount(),
      authority: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getSlashInstructionDataDecoder().decode(instruction.data),
  };
}
