/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { NOSANA_JOBS_PROGRAM_ADDRESS } from '../programs/index.js';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared/index.js';

export const ASSIGN_INSTRUCTION_ACCOUNTS = {
  job: 0,
  market: 1,
  run: 2,
  node: 3,
  user: 4,
  vault: 5,
  payer: 6,
  rewardsReflection: 7,
  rewardsVault: 8,
  authority: 9,
  rewardsProgram: 10,
  tokenProgram: 11,
  systemProgram: 12,
} as const;

export type AssignInstructionAccountName = keyof typeof ASSIGN_INSTRUCTION_ACCOUNTS;
export const ASSIGN_DISCRIMINATOR = new Uint8Array([
  73, 66, 125, 203, 81, 41, 64, 135,
]);

export function getAssignDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(ASSIGN_DISCRIMINATOR);
}

export type AssignInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountJob extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountRun extends string | AccountMeta<string> = string,
  TAccountNode extends string | AccountMeta<string> = string,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountRewardsReflection extends string | AccountMeta<string> = string,
  TAccountRewardsVault extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountRewardsProgram extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountJob extends string
        ? WritableSignerAccount<TAccountJob> & AccountSignerMeta<TAccountJob>
        : TAccountJob,
      TAccountMarket extends string
        ? WritableAccount<TAccountMarket>
        : TAccountMarket,
      TAccountRun extends string
        ? WritableSignerAccount<TAccountRun> & AccountSignerMeta<TAccountRun>
        : TAccountRun,
      TAccountNode extends string
        ? ReadonlyAccount<TAccountNode>
        : TAccountNode,
      TAccountUser extends string
        ? WritableAccount<TAccountUser>
        : TAccountUser,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountRewardsReflection extends string
        ? WritableAccount<TAccountRewardsReflection>
        : TAccountRewardsReflection,
      TAccountRewardsVault extends string
        ? WritableAccount<TAccountRewardsVault>
        : TAccountRewardsVault,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountRewardsProgram extends string
        ? ReadonlyAccount<TAccountRewardsProgram>
        : TAccountRewardsProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type AssignInstructionData = {
  discriminator: ReadonlyUint8Array;
  ipfsJob: ReadonlyUint8Array;
  timeout: bigint;
};

export type AssignInstructionDataArgs = {
  ipfsJob: ReadonlyUint8Array;
  timeout: number | bigint;
};

export function getAssignInstructionDataEncoder(): FixedSizeEncoder<AssignInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['ipfsJob', fixEncoderSize(getBytesEncoder(), 32)],
      ['timeout', getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: ASSIGN_DISCRIMINATOR })
  );
}

export function getAssignInstructionDataDecoder(): FixedSizeDecoder<AssignInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['ipfsJob', fixDecoderSize(getBytesDecoder(), 32)],
    ['timeout', getI64Decoder()],
  ]);
}

export function getAssignInstructionDataCodec(): FixedSizeCodec<
  AssignInstructionDataArgs,
  AssignInstructionData
> {
  return combineCodec(
    getAssignInstructionDataEncoder(),
    getAssignInstructionDataDecoder()
  );
}

export type AssignInput<
  TAccountJob extends string = string,
  TAccountMarket extends string = string,
  TAccountRun extends string = string,
  TAccountNode extends string = string,
  TAccountUser extends string = string,
  TAccountVault extends string = string,
  TAccountPayer extends string = string,
  TAccountRewardsReflection extends string = string,
  TAccountRewardsVault extends string = string,
  TAccountAuthority extends string = string,
  TAccountRewardsProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  job: TransactionSigner<TAccountJob>;
  market: Address<TAccountMarket>;
  run: TransactionSigner<TAccountRun>;
  node: Address<TAccountNode>;
  user: Address<TAccountUser>;
  vault: Address<TAccountVault>;
  payer: TransactionSigner<TAccountPayer>;
  rewardsReflection: Address<TAccountRewardsReflection>;
  rewardsVault: Address<TAccountRewardsVault>;
  authority: TransactionSigner<TAccountAuthority>;
  rewardsProgram: Address<TAccountRewardsProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  ipfsJob: AssignInstructionDataArgs['ipfsJob'];
  timeout: AssignInstructionDataArgs['timeout'];
};

export function getAssignInstruction<
  TAccountJob extends string,
  TAccountMarket extends string,
  TAccountRun extends string,
  TAccountNode extends string,
  TAccountUser extends string,
  TAccountVault extends string,
  TAccountPayer extends string,
  TAccountRewardsReflection extends string,
  TAccountRewardsVault extends string,
  TAccountAuthority extends string,
  TAccountRewardsProgram extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
>(
  input: AssignInput<
    TAccountJob,
    TAccountMarket,
    TAccountRun,
    TAccountNode,
    TAccountUser,
    TAccountVault,
    TAccountPayer,
    TAccountRewardsReflection,
    TAccountRewardsVault,
    TAccountAuthority,
    TAccountRewardsProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): AssignInstruction<
  TProgramAddress,
  TAccountJob,
  TAccountMarket,
  TAccountRun,
  TAccountNode,
  TAccountUser,
  TAccountVault,
  TAccountPayer,
  TAccountRewardsReflection,
  TAccountRewardsVault,
  TAccountAuthority,
  TAccountRewardsProgram,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOSANA_JOBS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    job: { value: input.job ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: true },
    run: { value: input.run ?? null, isWritable: true },
    node: { value: input.node ?? null, isWritable: false },
    user: { value: input.user ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    payer: { value: input.payer ?? null, isWritable: true },
    rewardsReflection: {
      value: input.rewardsReflection ?? null,
      isWritable: true,
    },
    rewardsVault: { value: input.rewardsVault ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
    rewardsProgram: { value: input.rewardsProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.job),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.run),
      getAccountMeta(accounts.node),
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.rewardsReflection),
      getAccountMeta(accounts.rewardsVault),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.rewardsProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getAssignInstructionDataEncoder().encode(
      args as AssignInstructionDataArgs
    ),
    programAddress,
  } as AssignInstruction<
    TProgramAddress,
    TAccountJob,
    TAccountMarket,
    TAccountRun,
    TAccountNode,
    TAccountUser,
    TAccountVault,
    TAccountPayer,
    TAccountRewardsReflection,
    TAccountRewardsVault,
    TAccountAuthority,
    TAccountRewardsProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedAssignInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    job: TAccountMetas[0];
    market: TAccountMetas[1];
    run: TAccountMetas[2];
    node: TAccountMetas[3];
    user: TAccountMetas[4];
    vault: TAccountMetas[5];
    payer: TAccountMetas[6];
    rewardsReflection: TAccountMetas[7];
    rewardsVault: TAccountMetas[8];
    authority: TAccountMetas[9];
    rewardsProgram: TAccountMetas[10];
    tokenProgram: TAccountMetas[11];
    systemProgram: TAccountMetas[12];
  };
  data: AssignInstructionData;
};

export function parseAssignInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedAssignInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 13) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      job: getNextAccount(),
      market: getNextAccount(),
      run: getNextAccount(),
      node: getNextAccount(),
      user: getNextAccount(),
      vault: getNextAccount(),
      payer: getNextAccount(),
      rewardsReflection: getNextAccount(),
      rewardsVault: getNextAccount(),
      authority: getNextAccount(),
      rewardsProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getAssignInstructionDataDecoder().decode(instruction.data),
  };
}
