/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from '@solana/kit';
import { NOSANA_JOBS_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLEAN_DISCRIMINATOR = new Uint8Array([
  250, 191, 56, 128, 150, 251, 1, 103,
]);

export function getCleanDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CLEAN_DISCRIMINATOR);
}

export type CleanInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountJob extends string | IAccountMeta<string> = string,
  TAccountMarket extends string | IAccountMeta<string> = string,
  TAccountPayer extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountJob extends string ? WritableAccount<TAccountJob> : TAccountJob,
      TAccountMarket extends string
        ? ReadonlyAccount<TAccountMarket>
        : TAccountMarket,
      TAccountPayer extends string
        ? WritableAccount<TAccountPayer>
        : TAccountPayer,
      ...TRemainingAccounts,
    ]
  >;

export type CleanInstructionData = { discriminator: ReadonlyUint8Array };

export type CleanInstructionDataArgs = {};

export function getCleanInstructionDataEncoder(): Encoder<CleanInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLEAN_DISCRIMINATOR })
  );
}

export function getCleanInstructionDataDecoder(): Decoder<CleanInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCleanInstructionDataCodec(): Codec<
  CleanInstructionDataArgs,
  CleanInstructionData
> {
  return combineCodec(
    getCleanInstructionDataEncoder(),
    getCleanInstructionDataDecoder()
  );
}

export type CleanInput<
  TAccountJob extends string = string,
  TAccountMarket extends string = string,
  TAccountPayer extends string = string,
> = {
  job: Address<TAccountJob>;
  market: Address<TAccountMarket>;
  payer: Address<TAccountPayer>;
};

export function getCleanInstruction<
  TAccountJob extends string,
  TAccountMarket extends string,
  TAccountPayer extends string,
  TProgramAddress extends Address = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
>(
  input: CleanInput<TAccountJob, TAccountMarket, TAccountPayer>,
  config?: { programAddress?: TProgramAddress }
): CleanInstruction<
  TProgramAddress,
  TAccountJob,
  TAccountMarket,
  TAccountPayer
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOSANA_JOBS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    job: { value: input.job ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: false },
    payer: { value: input.payer ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.job),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.payer),
    ],
    programAddress,
    data: getCleanInstructionDataEncoder().encode({}),
  } as CleanInstruction<
    TProgramAddress,
    TAccountJob,
    TAccountMarket,
    TAccountPayer
  >;

  return instruction;
}

export type ParsedCleanInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    job: TAccountMetas[0];
    market: TAccountMetas[1];
    payer: TAccountMetas[2];
  };
  data: CleanInstructionData;
};

export function parseCleanInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedCleanInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      job: getNextAccount(),
      market: getNextAccount(),
      payer: getNextAccount(),
    },
    data: getCleanInstructionDataDecoder().decode(instruction.data),
  };
}
