/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { NOSANA_JOBS_PROGRAM_ADDRESS } from '../programs/index.js';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared/index.js';

export const DELIST_INSTRUCTION_ACCOUNTS = {
  job: 0,
  market: 1,
  deposit: 2,
  payer: 3,
  vault: 4,
  tokenProgram: 5,
  authority: 6,
} as const;

export type DelistInstructionAccountName = keyof typeof DELIST_INSTRUCTION_ACCOUNTS;
export const DELIST_DISCRIMINATOR = new Uint8Array([
  55, 136, 205, 107, 107, 173, 4, 31,
]);

export function getDelistDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(DELIST_DISCRIMINATOR);
}

export type DelistInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountJob extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountDeposit extends string | AccountMeta<string> = string,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountJob extends string ? WritableAccount<TAccountJob> : TAccountJob,
      TAccountMarket extends string
        ? WritableAccount<TAccountMarket>
        : TAccountMarket,
      TAccountDeposit extends string
        ? WritableAccount<TAccountDeposit>
        : TAccountDeposit,
      TAccountPayer extends string
        ? WritableAccount<TAccountPayer>
        : TAccountPayer,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type DelistInstructionData = { discriminator: ReadonlyUint8Array };

export type DelistInstructionDataArgs = {};

export function getDelistInstructionDataEncoder(): FixedSizeEncoder<DelistInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: DELIST_DISCRIMINATOR })
  );
}

export function getDelistInstructionDataDecoder(): FixedSizeDecoder<DelistInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getDelistInstructionDataCodec(): FixedSizeCodec<
  DelistInstructionDataArgs,
  DelistInstructionData
> {
  return combineCodec(
    getDelistInstructionDataEncoder(),
    getDelistInstructionDataDecoder()
  );
}

export type DelistInput<
  TAccountJob extends string = string,
  TAccountMarket extends string = string,
  TAccountDeposit extends string = string,
  TAccountPayer extends string = string,
  TAccountVault extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAuthority extends string = string,
> = {
  job: Address<TAccountJob>;
  market: Address<TAccountMarket>;
  deposit: Address<TAccountDeposit>;
  payer: Address<TAccountPayer>;
  vault: Address<TAccountVault>;
  tokenProgram?: Address<TAccountTokenProgram>;
  authority: TransactionSigner<TAccountAuthority>;
};

export function getDelistInstruction<
  TAccountJob extends string,
  TAccountMarket extends string,
  TAccountDeposit extends string,
  TAccountPayer extends string,
  TAccountVault extends string,
  TAccountTokenProgram extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
>(
  input: DelistInput<
    TAccountJob,
    TAccountMarket,
    TAccountDeposit,
    TAccountPayer,
    TAccountVault,
    TAccountTokenProgram,
    TAccountAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): DelistInstruction<
  TProgramAddress,
  TAccountJob,
  TAccountMarket,
  TAccountDeposit,
  TAccountPayer,
  TAccountVault,
  TAccountTokenProgram,
  TAccountAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOSANA_JOBS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    job: { value: input.job ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: true },
    deposit: { value: input.deposit ?? null, isWritable: true },
    payer: { value: input.payer ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.job),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.deposit),
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.authority),
    ],
    data: getDelistInstructionDataEncoder().encode({}),
    programAddress,
  } as DelistInstruction<
    TProgramAddress,
    TAccountJob,
    TAccountMarket,
    TAccountDeposit,
    TAccountPayer,
    TAccountVault,
    TAccountTokenProgram,
    TAccountAuthority
  >);
}

export type ParsedDelistInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    job: TAccountMetas[0];
    market: TAccountMetas[1];
    deposit: TAccountMetas[2];
    payer: TAccountMetas[3];
    vault: TAccountMetas[4];
    tokenProgram: TAccountMetas[5];
    authority: TAccountMetas[6];
  };
  data: DelistInstructionData;
};

export function parseDelistInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedDelistInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      job: getNextAccount(),
      market: getNextAccount(),
      deposit: getNextAccount(),
      payer: getNextAccount(),
      vault: getNextAccount(),
      tokenProgram: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getDelistInstructionDataDecoder().decode(instruction.data),
  };
}
