/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { NOSANA_JOBS_PROGRAM_ADDRESS } from '../programs/index.js';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared/index.js';

export const END_DISCRIMINATOR = new Uint8Array([
  180, 160, 249, 217, 194, 121, 70, 16,
]);

export function getEndDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(END_DISCRIMINATOR);
}

export type EndInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountJob extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountRun extends string | AccountMeta<string> = string,
  TAccountDeposit extends string | AccountMeta<string> = string,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountJob extends string ? WritableAccount<TAccountJob> : TAccountJob,
      TAccountMarket extends string
        ? ReadonlyAccount<TAccountMarket>
        : TAccountMarket,
      TAccountRun extends string ? WritableAccount<TAccountRun> : TAccountRun,
      TAccountDeposit extends string
        ? WritableAccount<TAccountDeposit>
        : TAccountDeposit,
      TAccountUser extends string
        ? WritableAccount<TAccountUser>
        : TAccountUser,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountPayer extends string
        ? WritableAccount<TAccountPayer>
        : TAccountPayer,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type EndInstructionData = { discriminator: ReadonlyUint8Array };

export type EndInstructionDataArgs = {};

export function getEndInstructionDataEncoder(): FixedSizeEncoder<EndInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: END_DISCRIMINATOR })
  );
}

export function getEndInstructionDataDecoder(): FixedSizeDecoder<EndInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getEndInstructionDataCodec(): FixedSizeCodec<
  EndInstructionDataArgs,
  EndInstructionData
> {
  return combineCodec(
    getEndInstructionDataEncoder(),
    getEndInstructionDataDecoder()
  );
}

export type EndInput<
  TAccountJob extends string = string,
  TAccountMarket extends string = string,
  TAccountRun extends string = string,
  TAccountDeposit extends string = string,
  TAccountUser extends string = string,
  TAccountVault extends string = string,
  TAccountPayer extends string = string,
  TAccountAuthority extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  job: Address<TAccountJob>;
  market: Address<TAccountMarket>;
  run: Address<TAccountRun>;
  deposit: Address<TAccountDeposit>;
  user: Address<TAccountUser>;
  vault: Address<TAccountVault>;
  payer: Address<TAccountPayer>;
  authority: TransactionSigner<TAccountAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getEndInstruction<
  TAccountJob extends string,
  TAccountMarket extends string,
  TAccountRun extends string,
  TAccountDeposit extends string,
  TAccountUser extends string,
  TAccountVault extends string,
  TAccountPayer extends string,
  TAccountAuthority extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
>(
  input: EndInput<
    TAccountJob,
    TAccountMarket,
    TAccountRun,
    TAccountDeposit,
    TAccountUser,
    TAccountVault,
    TAccountPayer,
    TAccountAuthority,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): EndInstruction<
  TProgramAddress,
  TAccountJob,
  TAccountMarket,
  TAccountRun,
  TAccountDeposit,
  TAccountUser,
  TAccountVault,
  TAccountPayer,
  TAccountAuthority,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOSANA_JOBS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    job: { value: input.job ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: false },
    run: { value: input.run ?? null, isWritable: true },
    deposit: { value: input.deposit ?? null, isWritable: true },
    user: { value: input.user ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    payer: { value: input.payer ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.job),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.run),
      getAccountMeta(accounts.deposit),
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getEndInstructionDataEncoder().encode({}),
    programAddress,
  } as EndInstruction<
    TProgramAddress,
    TAccountJob,
    TAccountMarket,
    TAccountRun,
    TAccountDeposit,
    TAccountUser,
    TAccountVault,
    TAccountPayer,
    TAccountAuthority,
    TAccountTokenProgram
  >);
}

export type ParsedEndInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    job: TAccountMetas[0];
    market: TAccountMetas[1];
    run: TAccountMetas[2];
    deposit: TAccountMetas[3];
    user: TAccountMetas[4];
    vault: TAccountMetas[5];
    payer: TAccountMetas[6];
    authority: TAccountMetas[7];
    tokenProgram: TAccountMetas[8];
  };
  data: EndInstructionData;
};

export function parseEndInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedEndInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      job: getNextAccount(),
      market: getNextAccount(),
      run: getNextAccount(),
      deposit: getNextAccount(),
      user: getNextAccount(),
      vault: getNextAccount(),
      payer: getNextAccount(),
      authority: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getEndInstructionDataDecoder().decode(instruction.data),
  };
}
