/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { NOSANA_JOBS_PROGRAM_ADDRESS } from '../programs/index.js';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared/index.js';

export const QUIT_INSTRUCTION_ACCOUNTS = {
  job: 0,
  run: 1,
  payer: 2,
  authority: 3,
} as const;

export type QuitInstructionAccountName = keyof typeof QUIT_INSTRUCTION_ACCOUNTS;
export const QUIT_DISCRIMINATOR = new Uint8Array([
  191, 103, 141, 240, 80, 129, 103, 153,
]);

export function getQuitDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(QUIT_DISCRIMINATOR);
}

export type QuitInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountJob extends string | AccountMeta<string> = string,
  TAccountRun extends string | AccountMeta<string> = string,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountJob extends string ? WritableAccount<TAccountJob> : TAccountJob,
      TAccountRun extends string ? WritableAccount<TAccountRun> : TAccountRun,
      TAccountPayer extends string
        ? WritableAccount<TAccountPayer>
        : TAccountPayer,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type QuitInstructionData = { discriminator: ReadonlyUint8Array };

export type QuitInstructionDataArgs = {};

export function getQuitInstructionDataEncoder(): FixedSizeEncoder<QuitInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: QUIT_DISCRIMINATOR })
  );
}

export function getQuitInstructionDataDecoder(): FixedSizeDecoder<QuitInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getQuitInstructionDataCodec(): FixedSizeCodec<
  QuitInstructionDataArgs,
  QuitInstructionData
> {
  return combineCodec(
    getQuitInstructionDataEncoder(),
    getQuitInstructionDataDecoder()
  );
}

export type QuitInput<
  TAccountJob extends string = string,
  TAccountRun extends string = string,
  TAccountPayer extends string = string,
  TAccountAuthority extends string = string,
> = {
  job: Address<TAccountJob>;
  run: Address<TAccountRun>;
  payer: Address<TAccountPayer>;
  authority: TransactionSigner<TAccountAuthority>;
};

export function getQuitInstruction<
  TAccountJob extends string,
  TAccountRun extends string,
  TAccountPayer extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
>(
  input: QuitInput<TAccountJob, TAccountRun, TAccountPayer, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress }
): QuitInstruction<
  TProgramAddress,
  TAccountJob,
  TAccountRun,
  TAccountPayer,
  TAccountAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOSANA_JOBS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    job: { value: input.job ?? null, isWritable: true },
    run: { value: input.run ?? null, isWritable: true },
    payer: { value: input.payer ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.job),
      getAccountMeta(accounts.run),
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.authority),
    ],
    data: getQuitInstructionDataEncoder().encode({}),
    programAddress,
  } as QuitInstruction<
    TProgramAddress,
    TAccountJob,
    TAccountRun,
    TAccountPayer,
    TAccountAuthority
  >);
}

export type ParsedQuitInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    job: TAccountMetas[0];
    run: TAccountMetas[1];
    payer: TAccountMetas[2];
    authority: TAccountMetas[3];
  };
  data: QuitInstructionData;
};

export function parseQuitInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedQuitInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      job: getNextAccount(),
      run: getNextAccount(),
      payer: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getQuitInstructionDataDecoder().decode(instruction.data),
  };
}
