/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { NOSANA_JOBS_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const RECOVER_DISCRIMINATOR = new Uint8Array([
  108, 216, 38, 58, 109, 146, 116, 17,
]);

export function getRecoverDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(RECOVER_DISCRIMINATOR);
}

export type RecoverInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountJob extends string | IAccountMeta<string> = string,
  TAccountMarket extends string | IAccountMeta<string> = string,
  TAccountVault extends string | IAccountMeta<string> = string,
  TAccountUser extends string | IAccountMeta<string> = string,
  TAccountPayer extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountJob extends string ? WritableAccount<TAccountJob> : TAccountJob,
      TAccountMarket extends string
        ? ReadonlyAccount<TAccountMarket>
        : TAccountMarket,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountUser extends string
        ? WritableAccount<TAccountUser>
        : TAccountUser,
      TAccountPayer extends string
        ? WritableAccount<TAccountPayer>
        : TAccountPayer,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type RecoverInstructionData = { discriminator: ReadonlyUint8Array };

export type RecoverInstructionDataArgs = {};

export function getRecoverInstructionDataEncoder(): Encoder<RecoverInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: RECOVER_DISCRIMINATOR })
  );
}

export function getRecoverInstructionDataDecoder(): Decoder<RecoverInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getRecoverInstructionDataCodec(): Codec<
  RecoverInstructionDataArgs,
  RecoverInstructionData
> {
  return combineCodec(
    getRecoverInstructionDataEncoder(),
    getRecoverInstructionDataDecoder()
  );
}

export type RecoverInput<
  TAccountJob extends string = string,
  TAccountMarket extends string = string,
  TAccountVault extends string = string,
  TAccountUser extends string = string,
  TAccountPayer extends string = string,
  TAccountAuthority extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  job: Address<TAccountJob>;
  market: Address<TAccountMarket>;
  vault: Address<TAccountVault>;
  user: Address<TAccountUser>;
  payer: Address<TAccountPayer>;
  authority: TransactionSigner<TAccountAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getRecoverInstruction<
  TAccountJob extends string,
  TAccountMarket extends string,
  TAccountVault extends string,
  TAccountUser extends string,
  TAccountPayer extends string,
  TAccountAuthority extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
>(
  input: RecoverInput<
    TAccountJob,
    TAccountMarket,
    TAccountVault,
    TAccountUser,
    TAccountPayer,
    TAccountAuthority,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): RecoverInstruction<
  TProgramAddress,
  TAccountJob,
  TAccountMarket,
  TAccountVault,
  TAccountUser,
  TAccountPayer,
  TAccountAuthority,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOSANA_JOBS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    job: { value: input.job ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: false },
    vault: { value: input.vault ?? null, isWritable: true },
    user: { value: input.user ?? null, isWritable: true },
    payer: { value: input.payer ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.job),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getRecoverInstructionDataEncoder().encode({}),
  } as RecoverInstruction<
    TProgramAddress,
    TAccountJob,
    TAccountMarket,
    TAccountVault,
    TAccountUser,
    TAccountPayer,
    TAccountAuthority,
    TAccountTokenProgram
  >;

  return instruction;
}

export type ParsedRecoverInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    job: TAccountMetas[0];
    market: TAccountMetas[1];
    vault: TAccountMetas[2];
    user: TAccountMetas[3];
    payer: TAccountMetas[4];
    authority: TAccountMetas[5];
    tokenProgram: TAccountMetas[6];
  };
  data: RecoverInstructionData;
};

export function parseRecoverInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedRecoverInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      job: getNextAccount(),
      market: getNextAccount(),
      vault: getNextAccount(),
      user: getNextAccount(),
      payer: getNextAccount(),
      authority: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getRecoverInstructionDataDecoder().decode(instruction.data),
  };
}
