/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { NOSANA_JOBS_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_DISCRIMINATOR = new Uint8Array([
  219, 200, 88, 176, 158, 63, 253, 127,
]);

export function getUpdateDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(UPDATE_DISCRIMINATOR);
}

export type UpdateInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountMarket extends string | IAccountMeta<string> = string,
  TAccountAccessKey extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountMarket extends string
        ? WritableAccount<TAccountMarket>
        : TAccountMarket,
      TAccountAccessKey extends string
        ? ReadonlyAccount<TAccountAccessKey>
        : TAccountAccessKey,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateInstructionData = {
  discriminator: ReadonlyUint8Array;
  jobExpiration: bigint;
  jobPrice: bigint;
  jobType: number;
  nodeStakeMinimum: bigint;
  jobTimeout: bigint;
};

export type UpdateInstructionDataArgs = {
  jobExpiration: number | bigint;
  jobPrice: number | bigint;
  jobType: number;
  nodeStakeMinimum: number | bigint;
  jobTimeout: number | bigint;
};

export function getUpdateInstructionDataEncoder(): Encoder<UpdateInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['jobExpiration', getI64Encoder()],
      ['jobPrice', getU64Encoder()],
      ['jobType', getU8Encoder()],
      ['nodeStakeMinimum', getU128Encoder()],
      ['jobTimeout', getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_DISCRIMINATOR })
  );
}

export function getUpdateInstructionDataDecoder(): Decoder<UpdateInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['jobExpiration', getI64Decoder()],
    ['jobPrice', getU64Decoder()],
    ['jobType', getU8Decoder()],
    ['nodeStakeMinimum', getU128Decoder()],
    ['jobTimeout', getI64Decoder()],
  ]);
}

export function getUpdateInstructionDataCodec(): Codec<
  UpdateInstructionDataArgs,
  UpdateInstructionData
> {
  return combineCodec(
    getUpdateInstructionDataEncoder(),
    getUpdateInstructionDataDecoder()
  );
}

export type UpdateInput<
  TAccountMarket extends string = string,
  TAccountAccessKey extends string = string,
  TAccountAuthority extends string = string,
> = {
  market: Address<TAccountMarket>;
  accessKey: Address<TAccountAccessKey>;
  authority: TransactionSigner<TAccountAuthority>;
  jobExpiration: UpdateInstructionDataArgs['jobExpiration'];
  jobPrice: UpdateInstructionDataArgs['jobPrice'];
  jobType: UpdateInstructionDataArgs['jobType'];
  nodeStakeMinimum: UpdateInstructionDataArgs['nodeStakeMinimum'];
  jobTimeout: UpdateInstructionDataArgs['jobTimeout'];
};

export function getUpdateInstruction<
  TAccountMarket extends string,
  TAccountAccessKey extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
>(
  input: UpdateInput<TAccountMarket, TAccountAccessKey, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress }
): UpdateInstruction<
  TProgramAddress,
  TAccountMarket,
  TAccountAccessKey,
  TAccountAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOSANA_JOBS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    market: { value: input.market ?? null, isWritable: true },
    accessKey: { value: input.accessKey ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.accessKey),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getUpdateInstructionDataEncoder().encode(
      args as UpdateInstructionDataArgs
    ),
  } as UpdateInstruction<
    TProgramAddress,
    TAccountMarket,
    TAccountAccessKey,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedUpdateInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    market: TAccountMetas[0];
    accessKey: TAccountMetas[1];
    authority: TAccountMetas[2];
  };
  data: UpdateInstructionData;
};

export function parseUpdateInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedUpdateInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      market: getNextAccount(),
      accessKey: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getUpdateInstructionDataDecoder().decode(instruction.data),
  };
}
