/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { NOSANA_JOBS_PROGRAM_ADDRESS } from '../programs/index.js';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared/index.js';

export const WORK_INSTRUCTION_ACCOUNTS = {
  run: 0,
  market: 1,
  payer: 2,
  stake: 3,
  nft: 4,
  metadata: 5,
  authority: 6,
  systemProgram: 7,
} as const;

export type WorkInstructionAccountName = keyof typeof WORK_INSTRUCTION_ACCOUNTS;
export const WORK_DISCRIMINATOR = new Uint8Array([
  15, 67, 45, 195, 215, 137, 229, 47,
]);

export function getWorkDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(WORK_DISCRIMINATOR);
}

export type WorkInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountRun extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountStake extends string | AccountMeta<string> = string,
  TAccountNft extends string | AccountMeta<string> = string,
  TAccountMetadata extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountRun extends string
        ? WritableSignerAccount<TAccountRun> & AccountSignerMeta<TAccountRun>
        : TAccountRun,
      TAccountMarket extends string
        ? WritableAccount<TAccountMarket>
        : TAccountMarket,
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountStake extends string
        ? ReadonlyAccount<TAccountStake>
        : TAccountStake,
      TAccountNft extends string ? ReadonlyAccount<TAccountNft> : TAccountNft,
      TAccountMetadata extends string
        ? ReadonlyAccount<TAccountMetadata>
        : TAccountMetadata,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type WorkInstructionData = { discriminator: ReadonlyUint8Array };

export type WorkInstructionDataArgs = {};

export function getWorkInstructionDataEncoder(): FixedSizeEncoder<WorkInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: WORK_DISCRIMINATOR })
  );
}

export function getWorkInstructionDataDecoder(): FixedSizeDecoder<WorkInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getWorkInstructionDataCodec(): FixedSizeCodec<
  WorkInstructionDataArgs,
  WorkInstructionData
> {
  return combineCodec(
    getWorkInstructionDataEncoder(),
    getWorkInstructionDataDecoder()
  );
}

export type WorkInput<
  TAccountRun extends string = string,
  TAccountMarket extends string = string,
  TAccountPayer extends string = string,
  TAccountStake extends string = string,
  TAccountNft extends string = string,
  TAccountMetadata extends string = string,
  TAccountAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  run: TransactionSigner<TAccountRun>;
  market: Address<TAccountMarket>;
  payer: TransactionSigner<TAccountPayer>;
  stake: Address<TAccountStake>;
  nft: Address<TAccountNft>;
  metadata: Address<TAccountMetadata>;
  authority: TransactionSigner<TAccountAuthority>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getWorkInstruction<
  TAccountRun extends string,
  TAccountMarket extends string,
  TAccountPayer extends string,
  TAccountStake extends string,
  TAccountNft extends string,
  TAccountMetadata extends string,
  TAccountAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
>(
  input: WorkInput<
    TAccountRun,
    TAccountMarket,
    TAccountPayer,
    TAccountStake,
    TAccountNft,
    TAccountMetadata,
    TAccountAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): WorkInstruction<
  TProgramAddress,
  TAccountRun,
  TAccountMarket,
  TAccountPayer,
  TAccountStake,
  TAccountNft,
  TAccountMetadata,
  TAccountAuthority,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NOSANA_JOBS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    run: { value: input.run ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: true },
    payer: { value: input.payer ?? null, isWritable: true },
    stake: { value: input.stake ?? null, isWritable: false },
    nft: { value: input.nft ?? null, isWritable: false },
    metadata: { value: input.metadata ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.run),
      getAccountMeta(accounts.market),
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.stake),
      getAccountMeta(accounts.nft),
      getAccountMeta(accounts.metadata),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getWorkInstructionDataEncoder().encode({}),
    programAddress,
  } as WorkInstruction<
    TProgramAddress,
    TAccountRun,
    TAccountMarket,
    TAccountPayer,
    TAccountStake,
    TAccountNft,
    TAccountMetadata,
    TAccountAuthority,
    TAccountSystemProgram
  >);
}

export type ParsedWorkInstruction<
  TProgram extends string = typeof NOSANA_JOBS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    run: TAccountMetas[0];
    market: TAccountMetas[1];
    payer: TAccountMetas[2];
    stake: TAccountMetas[3];
    nft: TAccountMetas[4];
    metadata: TAccountMetas[5];
    authority: TAccountMetas[6];
    systemProgram: TAccountMetas[7];
  };
  data: WorkInstructionData;
};

export function parseWorkInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedWorkInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      run: getNextAccount(),
      market: getNextAccount(),
      payer: getNextAccount(),
      stake: getNextAccount(),
      nft: getNextAccount(),
      metadata: getNextAccount(),
      authority: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getWorkInstructionDataDecoder().decode(instruction.data),
  };
}
