stages:
  - prepare
  - test
  - build
  - deploy

variables:
__VARIABLES_BLOCK__

include:
  - local: .gitlab/ci/common.yml
  - local: .gitlab/ci/noop.yml
  - local: .gitlab/ci/generated-clients.yml
  - local: .gitlab/ci/release.yml
__INCLUDE_BLOCK__

