/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List jobs
         * @description List jobs with optional filtering by state, market, node, poster, and payer
         */
        get: operations["getJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/running": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get running jobs count per market */
        get: operations["getJobsRunning"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/running-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get running nodes for a market */
        get: operations["getJobsRunning-nodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/long-running": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get long-running jobs
         * @description Returns jobs running longer than their timeout, optionally filtered by market or payer
         */
        get: operations["getJobsLong-running"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job statistics
         * @description Get aggregated job statistics with optional grouping and time series (filter by market, node, poster, payer)
         */
        get: operations["getJobsStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/stats/timestamps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job timestamps */
        get: operations["getJobsStatsTimestamps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/stats/timestamps-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get GPU compute hours over time
         * @description Time series of GPU compute hours (sum of effective completed-job runtime) bucketed by period, mirroring /stats/timestamps but with hours instead of job counts.
         */
        get: operations["getJobsStatsTimestamps-hours"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count jobs
         * @description Get total job count and counts per state (QUEUED, RUNNING, COMPLETED, STOPPED), with optional filtering by market, node, project, and payer
         */
        get: operations["getJobsCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get jobs by addresses
         * @description Retrieve multiple jobs by a list of addresses (full job fields except jobDefinition and jobResult). Maximum of 100 addresses per request.
         */
        post: operations["postJobsBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job by address
         * @description Retrieve a job account by its address
         */
        get: operations["getJobsByAddress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get NOS price for a date or timestamp
         * @description Returns the NOS price (USD). Defaults to current time when neither timestamp nor date is provided. Query: timestamp (Unix seconds), date (YYYY-MM-DD), or omit for now; optional maxAgeMinutes for cache tolerance.
         */
        get: operations["getStatsPrice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the latest statistics */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/spending-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Flexible endpoint to retrieve spending history with custom date ranges and grouping options. */
        get: operations["getStatsSpending-history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/earning-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Flexible endpoint to retrieve earning history of node with custom date ranges and grouping options. */
        get: operations["getStatsEarning-history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getJobs: {
        parameters: {
            query?: {
                limit?: string | number;
                offset?: string | number;
                state?: "QUEUED" | "RUNNING" | "COMPLETED" | "STOPPED";
                market?: string;
                node?: string;
                poster?: string;
                payer?: string;
                timeStart?: string | number;
                timeEnd?: string | number;
                groupBy?: "project" | "market";
                timeSeriesInterval?: "day" | "week" | "month";
                useMultiplier?: boolean | string;
                skipCache?: boolean | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getJobsRunning: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "getJobsRunning-nodes": {
        parameters: {
            query: {
                market: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "getJobsLong-running": {
        parameters: {
            query?: {
                market?: string;
                payer?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getJobsStats: {
        parameters: {
            query?: {
                limit?: string | number;
                offset?: string | number;
                state?: "QUEUED" | "RUNNING" | "COMPLETED" | "STOPPED";
                market?: string;
                node?: string;
                poster?: string;
                payer?: string;
                timeStart?: string | number;
                timeEnd?: string | number;
                groupBy?: "project" | "market";
                timeSeriesInterval?: "day" | "week" | "month";
                useMultiplier?: boolean | string;
                skipCache?: boolean | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getJobsStatsTimestamps: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "getJobsStatsTimestamps-hours": {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getJobsCount: {
        parameters: {
            query?: {
                market?: string;
                node?: string;
                poster?: string;
                payer?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total: number;
                        byState: {
                            QUEUED: number;
                            RUNNING: number;
                            COMPLETED: number;
                            STOPPED: number;
                        };
                    };
                    "multipart/form-data": {
                        total: number;
                        byState: {
                            QUEUED: number;
                            RUNNING: number;
                            COMPLETED: number;
                            STOPPED: number;
                        };
                    };
                    "text/plain": {
                        total: number;
                        byState: {
                            QUEUED: number;
                            RUNNING: number;
                            COMPLETED: number;
                            STOPPED: number;
                        };
                    };
                };
            };
        };
    };
    postJobsBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    addresses: string[];
                    limit?: string | number;
                };
                "multipart/form-data": {
                    addresses: string[];
                    limit?: string | number;
                };
                "text/plain": {
                    addresses: string[];
                    limit?: string | number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        address: string;
                        ipfsJob: (string | null) | null;
                        ipfsResult: (string | null) | null;
                        market: string;
                        node: string;
                        payer: string;
                        price: number;
                        project: string;
                        state: number;
                        type: (string | null) | null;
                        jobStatus: (string | null) | null;
                        timeEnd: number;
                        timeStart: number;
                        timeout: number;
                        usdRewardPerHour: (number | null) | null;
                        listedAt: (number | null) | null;
                    }[];
                    "multipart/form-data": {
                        id: number;
                        address: string;
                        ipfsJob: (string | null) | null;
                        ipfsResult: (string | null) | null;
                        market: string;
                        node: string;
                        payer: string;
                        price: number;
                        project: string;
                        state: number;
                        type: (string | null) | null;
                        jobStatus: (string | null) | null;
                        timeEnd: number;
                        timeStart: number;
                        timeout: number;
                        usdRewardPerHour: (number | null) | null;
                        listedAt: (number | null) | null;
                    }[];
                    "text/plain": {
                        id: number;
                        address: string;
                        ipfsJob: (string | null) | null;
                        ipfsResult: (string | null) | null;
                        market: string;
                        node: string;
                        payer: string;
                        price: number;
                        project: string;
                        state: number;
                        type: (string | null) | null;
                        jobStatus: (string | null) | null;
                        timeEnd: number;
                        timeStart: number;
                        timeout: number;
                        usdRewardPerHour: (number | null) | null;
                        listedAt: (number | null) | null;
                    }[];
                };
            };
        };
    };
    getJobsByAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                    "multipart/form-data": Record<string, never>;
                    "text/plain": Record<string, never>;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                    "multipart/form-data": {
                        message: string;
                    };
                    "text/plain": {
                        message: string;
                    };
                };
            };
        };
    };
    getStatsPrice: {
        parameters: {
            query?: {
                timestamp?: string;
                date?: string;
                maxAgeMinutes?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        price: number | null;
                    };
                    "multipart/form-data": {
                        price: number | null;
                    };
                    "text/plain": {
                        price: number | null;
                    };
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "getStatsSpending-history": {
        parameters: {
            query: {
                address: string;
                start_date: string;
                end_date?: string;
                group_by?: "day" | "month";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "getStatsEarning-history": {
        parameters: {
            query: {
                address: string;
                start_date: string;
                end_date?: string;
                group_by?: "day" | "month";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
