/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/** The `QueueType` describes the type of queue */
export const QueueType = {
  Job: "Job",
  Node: "Node",
  Empty: "Empty",
} as const;
export type QueueType = (typeof QueueType)[keyof typeof QueueType];

export type QueueTypeArgs = QueueType;

export function getQueueTypeEncoder(): FixedSizeEncoder<QueueTypeArgs> {
  return getEnumEncoder(QueueType);
}

export function getQueueTypeDecoder(): FixedSizeDecoder<QueueType> {
  return getEnumDecoder(QueueType);
}

export function getQueueTypeCodec(): FixedSizeCodec<QueueTypeArgs, QueueType> {
  return combineCodec(getQueueTypeEncoder(), getQueueTypeDecoder());
}
